Feat error404 page
Avdhesh-Varshney/WebMasterLog pull request #1009
Opened 2024-10-28 15:55 UTC by dev129

Hi @Avdhesh-Varshney 
Closes: #919 

- **Title:** Created 404 Error Landing Page
- **Name:** Devansh Vishwa
- **Identify yourself:** GSSoC Contributor 
### Describe the add-ons or changes you've made 📃
I have created the 404 Error Landing Page. The main file is located at `src/app/components/shared/NotFound.tsx` and imported in `src/app/[projectDomain]/page.tsx`. The page includes the design for the error 404, with relevant text and an option to navigate back to the homepage.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/5529bebd-031b-40e0-893f-feb30a8b99b6)

### Type of change ☑️
What sort of change have you made:
- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
Please review the layout and functionality of the 404 Error Landing Page. Let me know if any further changes are needed.

2024-10-28 15:56 UTC, dev129 commented
Hi @Avdhesh-Varshney , I did some changes , now please review my PR.

2024-10-28 16:23 UTC, Avdhesh-Varshney requested changes
Logo is not display.
![image](https://github.com/user-attachments/assets/affaa198-0a62-407d-8130-9a26805261d5)

Project is present inside the `webmasterlog` folder, why have you created package.json outside of it?

2024-10-28 16:23 UTC, Avdhesh-Varshney commented on package-lock.json
.

2024-10-28 16:23 UTC, Avdhesh-Varshney commented on package.json
.

2024-10-28 16:48 UTC, dev129 commented
Done @Avdhesh-Varshney , please check now.

2024-10-29 05:09 UTC, dev129 commented
Hi @Avdhesh-Varshney , please check the changes I have made and let me know if anythign else is needed.

2024-10-29 11:57 UTC, Avdhesh-Varshney approved these changes

2024-10-29 11:58 UTC, merged