Text editor
Avdhesh-Varshney/WebMasterLog pull request #1010
Opened 2024-10-28 17:36 UTC by Sancharisingh

Closes: #977 

- **Title:** Text Editor
- **Name:** Sanchari singh
- **Idenitfy yourself:** GSSOC ext and Hacktoberfest

### Describe the add-ons or changes you've made 📃
I added a project titled Text Editor in the React-JS Projects directory, within the Intermediate section. This Text Editor project brings essential text formatting capabilities, allowing users to create and edit content with various styling options.

### Screenshots 📷
<img width="1437" alt="Screenshot 2024-10-24 at 5 36 48 PM" src="https://github.com/user-attachments/assets/caba3dd8-4ab1-431c-8249-114ca3357e0f">

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-28 17:58 UTC, Zedoman commented
@Sancharisingh please provide a working video

2024-10-28 18:47 UTC, Sancharisingh commented
> @Sancharisingh please provide a working video

https://youtu.be/PXinp04QQcg

2024-10-31 04:35 UTC, Avdhesh-Varshney requested changes
Enlist your project in react Readme file

2024-10-31 04:35 UTC, Avdhesh-Varshney commented on React-JS-Projects/Intermediate/Text-Editor/Screenshot.webp
File name in small letters

2024-10-31 08:27 UTC, Avdhesh-Varshney approved these changes

2024-10-31 08:27 UTC, merged