Added descriptions for frontend projects in data.json
Avdhesh-Varshney/WebMasterLog pull request #1049
Opened 2024-12-22 08:52 UTC by Mayank-704

Closes: 1046

- **Title:** Added descriptions for frontend projects in `data.json`
- **Name:** Mayank Gupta
- **Idenitfy yourself:** KWOC Contributor 

### Describe the add-ons or changes you've made 📃
I added detailed descriptions for the frontend projects in the `data.json` file as part of the open-source contribution. These descriptions provide better clarity for the frontend project entries.
A sample:
- "description": "The hotstar-clone project is a web page that replicates the interface of the popular streaming platform Hotstar using HTML5, CSS3, and JavaScript. This project focuses on creating a responsive design with interactive features such as navigation, content highlights, and media sections. It’s a valuable project for practicing the integration of JavaScript with HTML and CSS to enhance interactivity and user engagement."

### Screenshots 📷

![screenshot webp](https://github.com/user-attachments/assets/35d592f6-a970-4c58-8a7e-1ad303c8a09e)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

Descriptions have been added in the `src/database/data.json` file for frontend projects. Please review and let me know if any adjustments are needed.

2024-12-23 07:11 UTC, Avdhesh-Varshney requested changes
- Resolve merge conflicts
- Link your issue properly
- Don't change indentation, only commit your work

2024-12-23 10:59 UTC, Mayank-704 commented
@Avdhesh-Varshney Do I need to close this PR and make a new one with single commit or I can do one more commit here for resolving merge conflict.

2024-12-23 11:14 UTC, Avdhesh-Varshney commented
> @Avdhesh-Varshney Do I need to close this PR and make a new one with single commit or I can do one more commit here for resolving merge conflict.

Yes, work in this pr

2024-12-23 16:01 UTC, Mayank-704 commented
@Avdhesh-Varshney  Done 
- Resolved Merge Conflict (Didn't do linting)
- Linked Issue Properly

2024-12-24 16:46 UTC, Avdhesh-Varshney requested changes

2024-12-24 16:46 UTC, Avdhesh-Varshney commented on src/database/data.json
> +        "description": "This project is a frontend replica of the popular e-commerce platform Amazon. It demonstrates key web development skills by implementing a visually appealing and responsive us
fix the indentation of description

2024-12-26 16:54 UTC, closed without merging