todo list created
Avdhesh-Varshney/WebMasterLog pull request #111
Opened 2024-02-21 14:03 UTC by Bishal-35

# Pull Request for WebMasterLog 💡

## Issue Title: 
To Do Application using React Js

- **Name of the project** : To Do Application
- **Category:** ReactJs
- **Name:** Bishal Karmakar
- **GitHub ID:** https://github.com/Bishal-35
- **Idenitfy yourself:** Developer

Closes: 
#10

### Describe the add-ons or changes you've made 📃

Created a React application using ReactJs which lets the user to create a ToDo List

## Type of change ☑️

What sort of change have you made:

-  Created react application which creates a todo list

## How Has This Been Tested? ⚙️

It has been tested it with all the possible ways available.

## Checklist: ☑️

- My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- This PR does not contain plagiarized content.
- I have performed a self-review of my own code.
- I have commented my code, particularly wherever it was hard to understand.
- I have made corresponding changes to the documentation.
- My changes generate no new warnings.
- I have added things that prove my fix is effective or that my feature works.
- Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷

![Screenshot 2024-02-20 212451](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/120501312/22725474-22d6-41f7-a615-4171d81240a8)

2024-02-21 16:10 UTC, Avdhesh-Varshney requested changes

2024-02-21 16:10 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/ToDo-List/README.md
@Bishal-35 follow the newly readme template and properly write how to use or run this project.

2024-02-21 16:38 UTC, Bishal-35 commented on React-JS-Projects/Basic/ToDo-List/README.md
can you please provide the link for new readme file

2024-02-21 17:11 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/ToDo-List/README.md
https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/.github/PROJECT-README-TEMPLATE.md

2024-02-21 17:32 UTC, Avdhesh-Varshney requested changes

2024-02-21 17:32 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/ToDo-List/README.md
Code style of readme is still not changed and you have still not written the instructions for how to run this project properly.

2024-02-22 10:37 UTC, Avdhesh-Varshney approved these changes
PR Approved 🎉

2024-02-22 10:42 UTC, merged

2024-02-22 10:48 UTC, Bishal-35 commented
Why is it assigned again?

On Thu, 22 Feb, 2024, 4:12 pm Avdhesh, ***@***.***> wrote:

> Assigned #111 <https://github.com/Avdhesh-Varshney/WebMasterLog/pull/111>
> to @Bishal-35 <https://github.com/Bishal-35>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Avdhesh-Varshney/WebMasterLog/pull/111#event-11889299368>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4XLIQDZABKMY3Y434IX3XLYU4OJXAVCNFSM6AAAAABDTDP7RWVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRHA4DSMRZHEZTMOA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***
> com>
>

2024-02-22 10:50 UTC, Avdhesh-Varshney commented
@Bishal-35 don't reply directly from email ok. And assigned is required so that it will update on JWOC leaderboard ok.