Ceaser Cipher Work has been done
Avdhesh-Varshney/WebMasterLog pull request #127
Opened 2024-05-11 22:55 UTC by Damini2004

## Pull Request for WebMasterLog 💡

### Issue Title: Ceaser Cipher conversion

- **Name of the project** : 
- **Category:** 
- **Name:** Damini Chachane
- **GitHub ID:** 
- **Idenitfy yourself:** GSSOC24

Closes: 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
I have added the algorithm via which we can easily convert the text.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Screenshots 📷
![dark](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/636abc7d-24d8-4d66-aac8-b0cadf96681c)
![light](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/129ed2e8-8a82-4495-a488-d79ba95135b9)

Uploading freecompress-Caesar Cipher and 7 more pages - Personal - Microsoft_ Edge 2024-05-12 04-14-06.mp4…

### Note to reviewers 📄
I generally designed the UI of ceaser cipher in basic format because the main concept behind the ceaser cipher is its conversion of text as per the keys. I posted commit in Frontend intermediate project.Kindly gothrough and suggest any improvement.

2024-05-12 03:20 UTC, Avdhesh-Varshney requested changes
@Damini2004 I think `cipher.css` and `style.css` have same code.
So, remove 1 file.
And follow the structure and guidelines mentioned in `CONTRIBUTING.md` file.
If you feel any queries, go through successful merged prs of `Front-end-Projects` OK.

2024-05-12 03:20 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Ceaser Cipher/ceaser_cipher.html
Format the code properly of all the files.

2024-05-12 03:20 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Ceaser Cipher/cipher.css
> +  /* textarea{
Remove any un-necessary code.

2024-05-12 03:20 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Ceaser Cipher/main.js
> +
remove any un-necessary new lines.

2024-05-12 06:27 UTC, Damini2004 commented
Hello sir @Avdhesh-Varshney  No sir Style.css and cipher.css contain different program that if user want dark theme then style.css will run and if user want light theme cipher.css will run.
As you mentioned to format the html document,and rremove unnecessary javascript program i have resolve that issue

2024-05-12 17:33 UTC, Avdhesh-Varshney requested changes
@Damini2004 Everything is perfect.
But i have told for reviewing because you have not read guidelines properly.
- Change directory `Ceaser-Cipher`.
- And add a screenshot with extension of webp as `screenshot.webp`.
- Also you have included a `README.md` file.

Now, if you have any query, either go through merged PR's or tag me in GSSOC server.

2024-05-12 18:38 UTC, Damini2004 commented
Ceaser Cipher Conversion Project #127

2024-05-15 10:36 UTC, Avdhesh-Varshney requested changes
@Damini2004 
- See this PR is perfect [LINK](https://github.com/Avdhesh-Varshney/WebMasterLog/pull/131/files)
- I have provided you name with a hyphen and told you to read guidelines carefully.
- Still you have not attach 1 screenshot which have extension of webp format.

2024-05-15 10:36 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Ceaser Cipher/README.md
Follow this [README TEMPLATE](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/.github/PROJECT-README-TEMPLATE.md).

2024-05-15 10:43 UTC, Avdhesh-Varshney commented
@Damini2004 There is a suggestion to you. 
- If time exceedes more than 24 hrs, drop a msg in GSSOC server to either mentors or project admin (me) and 
- review the edited template of PR what i have changed for future contributions.

And there is a request to you, because of my fault, i had attach the front-end-projects label with this project but it is a vanilla-js-project. So, cut paste the project and resolve the above errors, commit all the changes in 1 go.

2024-05-17 10:43 UTC, closed without merging

2024-05-17 13:56 UTC, Damini2004 commented
Kinldy add GSSOC24  label with level that will be more beneficial for me under GSSOC Contributor.