added pomodoro timer website using react
Avdhesh-Varshney/WebMasterLog pull request #129
Opened 2024-05-12 14:20 UTC by VanshikaSabharwal

## Pull Request for WebMasterLog 💡

### Issue Title:  Pomodoro Timer Website using React JS 

- **Name of the project** : pomodoro-timer
- **Category:**  React
- **Name:** Vanshika Sabharwal
- **GitHub ID:**(https://github.com/VanshikaSabharwal)
- **Idenitfy yourself:**  GSSOC contributor

Closes: #55

### Describe the add-ons or changes you've made 📃

I have added React project pomodoro timer website to the project. 
This project has features like user-friendly interface, responsiveness, no extra stuff to distract user, clean code with comments wherever needed.

![Screenshot 2024-05-12 194542](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143436704/2b9363b0-a243-4887-bd31-37b7a1d70d03)

![Screenshot 2024-05-12 194609](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143436704/6d37ae89-3d2c-4cc1-9f9f-9726fea00749)

2024-05-12 17:27 UTC, Avdhesh-Varshney requested changes
@VanshikaSabharwal Go through guidelines. If you have any queries, go through other merged prs and their requested changes.

2024-05-12 17:27 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/pomodoro-timer/README.md
Follow the readme template as mentioned in guidelines.

2024-05-12 18:40 UTC, VanshikaSabharwal commented on React-JS-Projects/Basic/pomodoro-timer/README.md
I want to ask why did you removed level tag ? Will this issue not count?

2024-05-12 18:45 UTC, VanshikaSabharwal commented
I have added README.md file . So, can you please merge the project .

2024-05-13 19:11 UTC, VanshikaSabharwal commented
@Avdhesh-Varshney Can you please tell me what else must be added in the project. So that i can make the necessary changes for merge.

2024-05-15 10:46 UTC, Avdhesh-Varshney requested changes
@VanshikaSabharwal Still you have not read the guidelines carefully [Link](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md)

2024-05-15 10:58 UTC, VanshikaSabharwal commented
> @VanshikaSabharwal Still you have not read the guidelines carefully [Link](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md)



> @VanshikaSabharwal Still you have not read the guidelines carefully [Link](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md)

Okay, I'll do it

2024-05-15 10:59 UTC, VanshikaSabharwal commented
@Avdhesh-Varshney  Can you please add gssoc tag and level tag in small letter to this issue

2024-05-15 20:08 UTC, VanshikaSabharwal commented
I made changes @Avdhesh-Varshney in react.json and README.md file.

2024-05-15 20:09 UTC, VanshikaSabharwal commented
Also can you please add gssoc and level tag to this issue.

2024-05-17 10:46 UTC, Avdhesh-Varshney commented
> Also can you please add gssoc and level tag to this issue.

@VanshikaSabharwal labels will be add automatically when PR will be merged. If you have any query, tag me on discord i will response whenever possible.

2024-05-17 11:54 UTC, VanshikaSabharwal commented
Is there any changes to be made in the project . I have made all possible changes according to the guideliness.

## Pull Request for WebMasterLog 💡

### Issue Title: Pomodoro Timer Website using React 

- **Name of the project** : Pomodoro-Timer
- **Category:**  React
- **Name:** Vanshika
- **GitHub ID:** VanshikaSabharwal
- **Idenitfy yourself:** GSSOC


<!-- Mention the following details and these are mandatory -->

Closes: #55


### Describe the add-ons or changes you've made 📃
I have made a react project -> Pomodoro-Timer.
I have updated the README.md file of project, react.json file in database as well as i have made a README.md file for my Pomodor-Timer .
Also there is proper responsiveness in the Pomodoro-Timer and a 5 minute break after 25 minute work.


### Type of change ☑️
<!-- Please delete options that are not relevant. -->
What sort of change have you made:
<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️
<!-- Describe how it has been tested
Describe how have you verified the changes made -->



### Checklist: ☑️
<!--
Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.


### Screenshots 📷

![Screenshot 2024-05-12 194542](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/
![Screenshot 2024-05-12 194609](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143436704/a0a2fdba-d657-4ef3-b70b-498aca1843c0)
143436704/b3349092-aeac-4941-b701-e06208f99063)



### Note to reviewers 📄
<!-- Add notes to reviewers if applicable -->

2024-05-18 09:47 UTC, Avdhesh-Varshney reviewed
@VanshikaSabharwal this pr is too much messy and lots of un-necessary commits. So, create a new pr.
- i think screenshot is blank as 0 byte is mentioned. Properly attach after self verifying your screenshot and code.
- Don't update un-necessary code as done in `README.md` by deleting lines.
- name of directory is not `pomodoro-timer`. It's `Pomodoro-Timer` as mentioned in guidelines with proper example.
- No readme file is present to explain the project. That's why i told you to check other successfully merged PRs.

For further queries and doubts, join discord server [link](https://discord.gg/tSqtvHUJzE). Don't mess up the your PR. It will be useful for you in future for showcasing.

2024-05-18 09:53 UTC, closed without merging