Project Ceaser Cipher Conversion Project #127
Avdhesh-Varshney/WebMasterLog pull request #147
Opened 2024-05-15 19:04 UTC by Damini2004

## Pull Request for WebMasterLog 💡

### Issue Title: Ceaser Cipher Conversion Project #127 

- **Name of the project** : Ceaser Cipher Conversion Project 
- **Category:** Vanilla-JS-Projects
- **Name:** Damini Chachane
- **GitHub ID:**  https://github.com/Damini2004
- **Idenitfy yourself:** GSSOC Contributor

Closes: #127 

### Describe the add-ons or changes you've made 📃

Made a Cipher text language conversion which helps you in changing a ciphertext  into your plain language

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️
It has been tested on several text as per its key from ciphertext to plaintext and vice versa.

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Screenshots 📷
![dark](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/0200c0bc-0db1-4cc5-a59f-a559b35f0ff4)
![light](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/119414762/e544cfe9-aba8-4561-8b7d-68cdc03ac38f)

### Note to reviewers 📄
Kindly go throught it

2024-05-16 03:12 UTC, Avdhesh-Varshney requested changes
@Damini2004

2024-05-16 03:12 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Ceaser-Cipher/light.webp
Rename this file with `screenshot` name. 
And don't forget to update README file from `light.webp` to `screenshot.webp` file.

2024-05-17 10:39 UTC, Avdhesh-Varshney approved these changes
@Damini2004 PR Approved 🎉
But still you have not linked you issue with the PR. But i have linked it so take a review on it.

2024-05-17 10:42 UTC, merged

2024-05-17 13:59 UTC, Damini2004 commented
Kindly add GSSOC 24 label that will be more beneficial