Fixed navbar and also different branch
Avdhesh-Varshney/WebMasterLog pull request #160
Opened 2024-05-18 11:34 UTC by YadlaMani

## Pull Request for WebMasterLog 💡

### Issue Title: Adding a footer to the website

- **Name of the project** : 
- **Category:** 
- **Name:** 
- **GitHub ID:** 
- **Idenitfy yourself:** 

Closes:#142

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made
Added complete footer section
included social links,and repo links

### Type of change ☑️

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### How Has This Been Tested? ⚙️

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/133841094/25951164-960d-4985-a9a4-f438def95893)

### Note to reviewers 📄

2024-05-18 11:44 UTC, YadlaMani commented
@Avdhesh-Varshney pls review this

2024-05-19 02:12 UTC, Avdhesh-Varshney requested changes
@YadlaMani These extra spaces removes and converting single quote into double quote is not required. Just add your code only.

2024-05-19 02:12 UTC, Avdhesh-Varshney commented on src/App.jsx
A lots of un-necessary changes not in this file but many other files.
Keep your tab size by default 4 not 2.

2024-05-19 02:12 UTC, Avdhesh-Varshney commented on src/components/Pages/MainPage.jsx
Remove these un-necessary changes done by you.

2024-05-19 02:20 UTC, YadlaMani commented
@Avdhesh-Varshney but it's the general convection of writing standard code right

2024-05-19 02:38 UTC, closed without merging