Adding Pomodoro-Timer made using react.js
Avdhesh-Varshney/WebMasterLog pull request #161
Opened 2024-05-18 11:54 UTC by VanshikaSabharwal

## Pull Request for WebMasterLog 💡

### Issue Title: Pomodoro-Timer made using react.js

- **Name of the project** : Pomodor-Timer
- **Category:**  React.js
- **Name:**  Vanshika
- **GitHub ID:** [VanshikaSabharwal](https://github.com/VanshikaSabharwal)
- **Idenitfy yourself:**  GSSOC

Closes:  #55 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

I made a timer based on the pomodoro  technique which is 25minute work and 5 minute rest. So, after every 25 minutes , there will be a 5 minute rest. The design is easy to use and user-friendly as well as responsive. 

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

I have used ESLint for linting and testing to verify there is no bug.

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Screenshots 📷

![Screenshot 2024-05-12 194609](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143436704/b7611135-15db-489f-bdf1-9d10de4413be)
![Screenshot 2024-05-12 194542](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/143436704/09ce093a-3568-415c-8eb6-8aba8e06f53c)

2024-05-18 14:05 UTC, Avdhesh-Varshney requested changes
@VanshikaSabharwal PR Not Approved 🎉 
Same mistake again repeated as of last pr.

2024-05-18 14:05 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/pomodoro-timer/screenshot.webp
still ss is a empty file.

2024-05-18 14:05 UTC, Avdhesh-Varshney commented on React-JS-Projects/README.md
no correction same thing has done again.

2024-05-18 14:05 UTC, Avdhesh-Varshney commented on database/react.json
change your vs code tab size to 4 OK.

2024-05-18 14:36 UTC, VanshikaSabharwal commented on database/react.json
yes it's already 4

2024-05-19 04:39 UTC, VanshikaSabharwal reviewed
All files reviewed

2024-05-22 03:09 UTC, Avdhesh-Varshney reviewed
@VanshikaSabharwal leave this project, when you can't follow the guidelines properly.
This is too much to tell anyone again and again. This is not only waste of your time but my time also.

2024-05-22 06:30 UTC, closed without merging