Add-Url Scraper project under Node JS category
Avdhesh-Varshney/WebMasterLog pull request #166
Opened 2024-05-19 06:20 UTC by Rags-Mishra

## Pull Request for WebMasterLog 💡

### Issue Title:  URL Scraper using Node JS #49 

- **Name of the project** : Url-Scraper 
- **Category:** NodeJS
- **Name:** Ragini Mishra
- **GitHub ID:** Rags-Mishra #83007531
- **Idenitfy yourself:** GSSOC'24 Contributer

Closes: #49 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

The folder is thoroughly tested across various websites which contain different kinds of data. The results were assuring the functionality of feature.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/83007531/673bc200-2c64-4adb-8fbf-6310890de921)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/83007531/9c556b25-f424-46dd-bd9d-cdaef055ab2a)

### Note to reviewers 📄

2024-05-19 16:58 UTC, Avdhesh-Varshney requested changes
@Rags-Mishra you have neither read the guidelines nor read the main readme file.
Follow them properly. For further communication or doubt, join discord server https://discord.gg/tSqtvHUJzE

2024-05-20 04:48 UTC, Rags-Mishra commented
I missed including screenshot and update README.md file. I will certainly do so.

2024-05-22 05:59 UTC, Rags-Mishra commented
@Avdhesh-Varshney Kindly check the updates done.

2024-05-24 10:50 UTC, Avdhesh-Varshney requested changes
@Rags-Mishra Resolve these changes.

2024-05-24 10:50 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Url-Scraper/README.md
> +  <!-- ![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) -->
Comment out all of them so that they will be visible on the README file.

2024-05-24 10:50 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Url-Scraper/README.md
> +<h1 align='center'><b>💥 PROJECT NAME 💥</b></h1>
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/b61a257d-859a-4818-be55-8f6b72757d93)

Update the project name `URL-SCRAPER` in readme file.

2024-05-24 10:50 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Url-Scraper/README.md
> +- Web page user interface
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/4cd9c3f5-a361-4691-9958-88ef61a79049)

Any screenshot is not visible on the README file. Do it correct.

2024-05-30 05:28 UTC, Rags-Mishra commented
Updates are done. Kindly check.

2024-05-31 03:53 UTC, Avdhesh-Varshney requested changes
@Rags-Mishra One more changes, Keep your project inside the `Intermediate` directory.
As `Node-JS-Projects/Intermediate/Url-Scraper` Ok.

2024-05-31 12:15 UTC, Rags-Mishra commented
Okay.


On Fri, 31 May 2024 at 09:24, Avdhesh ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @Rags-Mishra <https://github.com/Rags-Mishra> One more changes, Keep your
> project inside the Intermediate directory.
> As Node-JS-Projects/Intermediate/Url-Scraper Ok.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Avdhesh-Varshney/WebMasterLog/pull/166#pullrequestreview-2089852710>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATZJQK2IV2U4LG2PHVDUGADZE7X6NAVCNFSM6AAAAABH6C7JASVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBZHA2TENZRGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-02 09:21 UTC, Avdhesh-Varshney approved these changes
@Rags-Mishra PR Approved 🎉
But you have to update your project in the main readme file as mentioned.
But now leave it, i will do it.

2024-06-02 09:23 UTC, merged