NASA Media Gallery
Avdhesh-Varshney/WebMasterLog pull request #210
Opened 2024-05-29 19:05 UTC by SonaliKumari2

## Pull Request for WebMasterLog 💡

### Issue Title: NASA Media Gallery

- **Name of the project** : NASA Media Gallery
- **Category:**  CSS, Front-end,  Vanilla JS, Documentation.
- **Name:** Sonali Kumari
- **GitHub ID:** SonaliKumari2
- **Idenitfy yourself:** Contributor

Closes: #116 

### Describe the add-ons or changes you've made 📃
NASA API to fetch images based on the topic entered by the user from NASA Gallery

Give a clear description of what have you added or modifications made

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### How Has This Been Tested? ⚙️
By running index.html .

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Screenshots 📷

![Screenshot 2024-05-21 134144](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/156329692/ea7657be-2299-4178-abb2-e2462bc71e03)

### Note to reviewers 📄
Review.

2024-05-31 03:41 UTC, Avdhesh-Varshney requested changes
@SonaliKumari2 Resolve these changes and join the discord server for further communication.

2024-05-31 03:41 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Netflix-Clone/README.md
Why this is edited?

2024-05-31 03:41 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/NASA-Media-Gallery/README.md
> +<h1 align='center'><b>💥 TO DO LIST 💥</b></h1>
carefully write the README file

2024-05-31 03:41 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/NASA-Media-Gallery/screenshot.webp/ss1.webp
there is not requirement of directory named `screenshot.webp`
I think you have to go through other merged prs of type `Vanilla-JS-Projects`.

2024-06-05 17:00 UTC, SonaliKumari2 commented
Yes, I am working on it. As I am a beginner, it is taking me time

On Wed, 5 Jun 2024, 9:41 pm Avdhesh, ***@***.***> wrote:

> @SonaliKumari2 <https://github.com/SonaliKumari2> are you working on it?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Avdhesh-Varshney/WebMasterLog/pull/210#issuecomment-2150450146>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFIWNXEUTXEIYU6XYBVWDBTZF42CRAVCNFSM6AAAAABIPQ2IJCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNJQGQ2TAMJUGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-10 17:50 UTC, SonaliKumari2 commented on Vanilla-JS-Projects/Basic/NASA-Media-Gallery/screenshot.webp/ss1.webp
what changes should i made in my readme.md file?

2024-06-14 06:08 UTC, Avdhesh-Varshney commented
@SonaliKumari2 again raise your pr by re-forking this project. It can't be approved.

2024-06-14 06:08 UTC, closed without merging