Password Generator using Vanilla JS #14
Avdhesh-Varshney/WebMasterLog pull request #23
Opened 2024-01-21 21:40 UTC by Hacxmr

# Pull Request for WebMasterLog 💡

## Issue Title: 
Password Generator using Vanilla JS #14

- **Name of the project** : Password Generator
- **Category:**  Vanilla Js
- **Name:** Mitali Raj
- **GitHub ID:** https://github.com/Hacxmr
- **Idenitfy yourself:** JWOC Contributor

Closes: 
#14

# Password Generator Web Page

## Overview
This HTML document creates a password generator web page. It features a heading, a display area for the generated password, and a button to trigger password generation. Users can also copy the generated password to the clipboard using an associated icon.

## Components
- Heading with a styled span for emphasis.
- Display area with an input field for the generated password.
- Copy icon for copying the password to the clipboard.
- "Generate Password" button.
- External CSS file (`style.css`) for styling.
- External JavaScript file (`script.js`) for handling functionality.

## Interaction
- Users can click the "Generate Password" button to generate a random password.
- The generated password can be copied to the clipboard using the copy icon.

## Note
- The actual functionality of generating and copying passwords is expected to be implemented in the linked JavaScript file (`script.js`).

## Checklist: ☑️

☑️My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project
☑️ This PR does not contain plagiarized content.
☑️ I have performed a self-review of my own code.
☑️ I have commented my code, particularly wherever it was hard to understand.
☑️ I have made corresponding changes to the documentation.
☑️ My changes generate no new warnings.
☑️ I have added things that prove my fix is effective or that my feature works.
☑️ Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷
<img width="922" alt="image" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/129144413/4dc3d8b0-effc-4067-be93-3a491ccbaf49">

2024-01-23 08:26 UTC, Avdhesh-Varshney requested changes
@Hacxmr directory name should be `Password-Generator` in kebab-case letters.

2024-01-23 08:26 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Password Generator/Readme.md
@Hacxmr Follow the readme template as mentioned in contributing guidelines.

2024-01-23 12:55 UTC, Hacxmr commented
@Avdhesh-Varshney I have made changes based on the requirement. Can you check and suggest any further modifications are needed

2024-01-23 14:04 UTC, Avdhesh-Varshney requested changes

2024-01-23 14:04 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Password-Generator/Readme.md
> +![Alt text](Password-Generator.webp)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/b747fc4f-2eed-4b72-ac3d-25610d55592d)

@Hacxmr Screenshot is not shown in readme file.
- You have to upload the pic on comment section, image link will be obtained for you.
- As i have done for the above pic `![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/5c50ad4e-c0ae-44f6-ac3a-36164af35496)`
- Then just copy that link and paste it.

2024-01-23 17:11 UTC, Hacxmr commented
Hey! @Avdhesh-Varshney  I have made changes based on the input still, I couldn't get a screenshot image. Kindly check

2024-01-24 08:31 UTC, Avdhesh-Varshney commented
@Hacxmr no problem i will do it.
PR Approved 🎉

2024-01-24 08:32 UTC, merged