Virtual piano
Avdhesh-Varshney/WebMasterLog pull request #289
Opened 2024-06-10 15:23 UTC by VaishnaviMankala19

Closes: #271

- **Title** : VIRTUAL PIANO
- **Name:** : MANKALA VAISHNAVI
- **Idenitfy yourself:** : gssoc24

### Describe the add-ons or changes you've made 📃
I have added Virtual-Piano in Vanilla.js>basic , updated readme and database

### How Has This Been Tested? ⚙️

### Screenshots 📷

![Screenshot (24)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/65650e85-3598-492b-bc79-3d427b6571bc)

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-06-11 03:37 UTC, Avdhesh-Varshney requested changes
@VaishnaviMankala19 LGTM. But change the directory named to `Virtual-Piano`

2024-06-11 03:37 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Virtual-piano/output.png
ss name is to be `screenshot.webp` i.e. not in png format it is required in webp format and change the name as it is.

2024-06-11 04:12 UTC, VaishnaviMankala19 commented
Can i get level2 for this @Avdhesh-Varshney

2024-06-12 05:29 UTC, Avdhesh-Varshney requested changes
@VaishnaviMankala19 change `Virtual-piano` folder name to `Virtual-Piano` and resolve the merge conflicts.

2024-06-14 05:28 UTC, VaishnaviMankala19 commented
@Avdhesh-Varshney please review my pr

2024-06-14 06:06 UTC, Avdhesh-Varshney commented
@VaishnaviMankala19 again raise your pr with proper guidelines. It can't be approved as there are 34 commits for a single project addition.

2024-06-14 06:06 UTC, closed without merging