Added Movie Finder
Avdhesh-Varshney/WebMasterLog pull request #293
Opened 2024-06-10 18:19 UTC by Asymtode712

Closes: #269 

- **Title** :  Movie Finder
- **Name:** : Siddheya Kulkarni
- **Idenitfy yourself:** : GSSoC Contributor

### Describe the add-ons or changes you've made 📃

I have added a Movie Finder through which users can easily find every possible information regarding a particular movie.

### How Has This Been Tested? ⚙️

The code has been tested in my local machine

### Screenshots 📷

![movie](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/115717746/3f6e0010-035d-49e4-ae8b-a3b59719a752)

### Type of change ☑️

What sort of change have you made:

- [X] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Note to reviewers 📄

Please review and merge this PR if it is good to go

2024-06-10 18:20 UTC, Asymtode712 commented
@Avdhesh-Varshney Sorry for closing the old PR as the things got messy there, please go through this PR and merge it if everything is okay

2024-06-11 03:47 UTC, Avdhesh-Varshney requested changes

2024-06-11 03:47 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Movie-Finder/README.md
> +![img](./screenshot.webp)
ss is not shown in readme file

2024-06-11 03:57 UTC, Asymtode712 commented
@Avdhesh-Varshney Done the requested change, kindly review

2024-06-11 04:07 UTC, Avdhesh-Varshney approved these changes
@Asymtode712 PR Approved 🎉

2024-06-11 04:07 UTC, merged