added Virtual-Piano
Avdhesh-Varshney/WebMasterLog pull request #320
Opened 2024-06-14 08:06 UTC by VaishnaviMankala19

Closes:  #271

- **Title** : Virtual-Piano
- **Name:** : MANKALA VAISHNAVI
- **Idenitfy yourself:** : GSSOC24

### Describe the add-ons or changes you've made 📃
I have added Virtual-Piano 

### How Has This Been Tested? ⚙️

### Screenshots 📷

![Screenshot (24)](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/131646799/1c361263-1ca9-41e2-85f1-ee2a178f58c8)

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-06-14 09:46 UTC, Avdhesh-Varshney requested changes

2024-06-14 09:46 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Virtual-Piano/README.md
> +<!-- directly add the link of video (If, possible) -->
remove this section, if video is not present.

2024-06-14 10:07 UTC, VaishnaviMankala19 commented
updated the changes that are mentioned

2024-06-15 02:35 UTC, Avdhesh-Varshney approved these changes
@VaishnaviMankala19 PR Approved 🎉
Carefully link your issue with pr

2024-06-15 02:35 UTC, merged