MakeMyTrip Clone Website #19
Avdhesh-Varshney/WebMasterLog pull request #34
Opened 2024-01-23 11:35 UTC by AryanPahuja21

# Pull Request for WebMasterLog 💡

## Issue Title: 
MakeMyTrip Clone Website #19

- **Name of the project:** MakeMyTrip-website-clone
- **Category:** CSS
- **Name:** Aryan Pahuja
- **GitHub ID:** https://github.com/AryanPahuja21
- **Idenitfy yourself:** JWOC'24 Contributor

Closes: 
#19 

### Describe the add-ons or changes you've made 📃

Created a clone of the website "make-my-trip" using HTML and CSS.

## Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷
![Cover image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139960070/170d4cb0-9bcf-46cc-aad2-1e71e4f1b074)

![Screenshot 2024-01-23 165202](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139960070/72026f6e-92a9-47ab-8925-422b9b6c1c3d)

## Note to reviewers 📄
Please go through my PR and review if any changes are to be done.

2024-01-23 14:17 UTC, Avdhesh-Varshney requested changes

2024-01-23 14:19 UTC, Avdhesh-Varshney commented
@AryanPahuja21 Create a folder `Front-end-Projects` named and inside in it create another directory with named `Intermediate`.
Keep you project there and also resolve the above conflicts and commit it again.

2024-01-23 15:39 UTC, AryanPahuja21 commented
@Avdhesh-Varshney I have made the changes as described by you. Please review.

2024-01-24 08:50 UTC, Avdhesh-Varshney approved these changes

2024-01-24 08:50 UTC, Avdhesh-Varshney commented
@AryanPahuja21 LGTM. PR Approved 🎉

2024-01-24 08:51 UTC, merged