code-editor added
Avdhesh-Varshney/WebMasterLog pull request #340
Opened 2024-06-17 06:32 UTC by maradadivyasree020

Closes: 1396

- **Title** : CodeEditor
- **Name:** : Marada Divya Sree
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
I have added my project CodeEditor . This is an code editor application built with React.js. It allows users to write, edit, and execute code snippets in programming languages like HTML,CSS,JS. The editor provides syntax highlighting, and other essential features to enhance the coding experience.

### How Has This Been Tested? ⚙️

Yes, I have tested it on my local computer.

### Screenshots 📷

![screenshot webp](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/132190190/6a474a7e-84b6-42a3-8193-621a0f723c33)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Note to reviewers 📄

2024-06-18 02:43 UTC, Avdhesh-Varshney requested changes
@maradadivyasree020 Looks good. But keep your project inside the `Advanced` projects directory as i've already assigned you `level3` ok.

2024-06-18 02:43 UTC, Avdhesh-Varshney commented on React-JS-Projects/Intermediate/Code-Editor/README.md
> +<img src='./screenshot.webp.png'>
after changing the ss update it here.

2024-06-18 02:43 UTC, Avdhesh-Varshney commented on React-JS-Projects/Intermediate/Code-Editor/screenshot.webp.png
`screenshot.webp` is not a name. Here `screenshot` is the name and `webp` is the extension of the ss file.
So, convert your png file into webp format and update it here.

2024-06-18 02:43 UTC, Avdhesh-Varshney commented on React-JS-Projects/README.md
I've assigned you `level3` to keep it under Advanced level project. Change the level from intermediate to advanced.

2024-06-18 02:43 UTC, Avdhesh-Varshney commented on database/react.json
> +		"tag": "Intermediate",
change tag here also to advanced.

2024-06-18 12:44 UTC, maradadivyasree020 commented on React-JS-Projects/Intermediate/Code-Editor/README.md
> +<img src='./screenshot.webp.png'>
sure

2024-06-18 12:59 UTC, maradadivyasree020 commented
I have made the required changes.

2024-06-19 07:13 UTC, Avdhesh-Varshney requested changes

2024-06-19 07:13 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/Code-Editor/screenshot.png
convert this png to webp format and resolve the merge conflicts.

2024-06-19 13:51 UTC, Avdhesh-Varshney approved these changes
@maradadivyasree020 PR Approved 🎉

2024-06-19 13:51 UTC, merged

2024-06-19 13:59 UTC, Avdhesh-Varshney commented
@maradadivyasree020 mention your issue properly with the pr