Project : Image Search Engine Frontend Project
Avdhesh-Varshney/WebMasterLog pull request #366
Opened 2024-06-21 06:27 UTC by GAVINESHWAR

Closes: 

issue : #351 
- **Title** : Image Search Engine
- **Name:** : G AVINESHWAR
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
I am contributed the Image Search Engine project to this WebMasterLog it is an Front end project developed using html, css, javascript and Api integration.

### How Has This Been Tested? ⚙️

### Screenshots 📷

![Screenshot 2024-06-21 115053](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/4e4309fd-f577-4283-ba24-47b98be662c5)
![Screenshot 2024-06-21 115223](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/124431955/9d2e4661-00e2-4785-a5bd-954dff287d46)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Note to reviewers 📄

I PR the issue @Avdhesh-Varshney check my changes and merge the changes to make contribution to our project sir. 

Thank you

2024-06-22 15:02 UTC, Avdhesh-Varshney requested changes
@GAVINESHWAR keep your project according to the tags assigned on your issue. So, keep it inside `Vanilla-JS` and `Basic` folder.

2024-06-22 15:02 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Image-Search-Engine/README.md
follow readme template and naming convention of ss is `screenshot.webp` not `Screenshot.webp`.

2024-06-22 15:22 UTC, GAVINESHWAR commented on Front-end-Projects/Intermediate/Image-Search-Engine/README.md
@Avdhesh-Varshney , I done all the changes which were instructed , so please check my changes and merge the PR sir.

Thank you

2024-06-24 05:45 UTC, closed without merging

2024-06-24 05:47 UTC, GAVINESHWAR commented
@Avdhesh-Varshney I closed the PR because of conflicts  and added new PR for this issue , so please check the changes of PR : #392 and merge the changes sir.

Thank you