Blog Website using NodeJS
Avdhesh-Varshney/WebMasterLog pull request #379
Opened 2024-06-22 02:14 UTC by DharshiBalasubramaniyam

Closes:  #15 

- **Title** :  Blog platform
- **Name:** : Dharshi Balasubramaniyam
- **Idenitfy yourself:** : GSSOC 24

### Describe the add-ons or changes you've made 📃

I have added a backend api for blog platform.

1. Backend infrastructure for a blogging platform, using Node.js, Express.js, and MongoDB, facilitating seamless management of user and admin roles with role-based authentication.
2. Robust user authentication functionalities, including sign-in and sign-up features, ensuring secure access for both users and administrators.
3. Users can create, edit, delete and view their own blogs.
4. Users can like/unlike, comment, search by tags and view blogs.
5. Administrators can manage user, blogs and tags.

### How Has This Been Tested? ⚙️

I have tested the apis via postman. Some of the screenshots are below.

## Screenshots 📷

![add_comment](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/53fcc256-667b-4ee0-810e-fde84c9251ca)
![create_blog](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/35eb27a5-4597-4795-9b2f-a30bb1092659)
![get_all_blogs](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/696ec8b8-8ee3-4324-b749-ec7ebeffd44e)
![get_all_tags](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/8ada812d-42c3-4030-9591-9217a0946f77)
![like_unlike](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/29e56b3c-74a1-49a0-ba07-6cede2a9ef2e)
![login_user](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/d8df731f-67d0-4493-96e7-b4a7a5cd1dd2)
![register_user](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/139672976/fc80818e-0fde-44f0-b6b9-12d78c82ab01)

### Type of change ☑️

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-06-22 15:27 UTC, Avdhesh-Varshney approved these changes
@DharshiBalasubramaniyam PR Approved 🎉

2024-06-22 15:29 UTC, Avdhesh-Varshney requested changes

2024-06-22 15:29 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Advanced/Blog-Platform/package-lock.json
@DharshiBalasubramaniyam remove this file. no need of it as package.json is load the required dependencies.

2024-06-22 15:37 UTC, DharshiBalasubramaniyam commented on Node-JS-Projects/Advanced/Blog-Platform/package-lock.json
done!

2024-06-25 08:44 UTC, Avdhesh-Varshney approved these changes

2024-06-25 08:45 UTC, merged