Travel
Avdhesh-Varshney/WebMasterLog pull request #395
Opened 2024-06-24 14:47 UTC by aditya-bhaumik

Closes: 

- **Title** :  Travel Website
- **Name:** : Aditya Bhaumik
- **Idenitfy yourself:** : GSSOC'24

### Describe the add-ons or changes you've made 📃

I have added travel website in React-Projects>Intermediate and also updated database , readme files

### How Has This Been Tested? ⚙️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
Fixes #21 

Sorry it took some time to make this website
Please review my pull request and add the gssoc label 
Thank you

2024-06-24 15:04 UTC, aditya-bhaumik commented
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/92214013/f45de115-0a80-45e4-93e4-95cbc1b9d6c2)

2024-06-25 09:59 UTC, Avdhesh-Varshney requested changes

2024-06-25 09:59 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/Travel-Website/README.md
> +    <img src='https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white' />
Mention your linkedin and github profile properly not just the tags.

2024-06-25 09:59 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/Travel-Website/public/screenshot.webp
keep it outside the public folder

2024-06-25 09:59 UTC, Avdhesh-Varshney commented
@aditya-bhaumik Also attach your assigned issue with the pr by editing the pr template

2024-06-25 10:09 UTC, aditya-bhaumik commented
@Avdhesh-Varshney i have made the changes requested

2024-06-25 10:15 UTC, Avdhesh-Varshney approved these changes
@aditya-bhaumik PR Approved 🎉

2024-06-25 10:16 UTC, merged

2024-06-25 10:16 UTC, Avdhesh-Varshney commented
@aditya-bhaumik don't create a large sequence of commits for a single pr.

2024-06-25 10:22 UTC, aditya-bhaumik commented
@Avdhesh-Varshney i am really sorry i will make sure not to do this mistake in the next project actually i had completed the project but for some reason i was not able to push the project using my terminal or git bash