Added Prime Number Checker: #397
Avdhesh-Varshney/WebMasterLog pull request #399
Opened 2024-06-25 14:08 UTC by Anshika14528

Closes:#397

- **Title** :  Prime Number Checker
- **Name:** : Anshika
- **Idenitfy yourself:** : GSSOC

Added the prime number checker used to check if number is prime or not.

### How Has This Been Tested? ⚙️
I have tested it on my own.

### Screenshots 📷
<img width="1450" alt="Screenshot 2024-06-25 at 7 23 03 PM" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/168436423/96670f3a-df69-4b96-944b-adf9c9cb01da">
<img width="1459" alt="screen" src="https://github.com/Avdhesh-Varshney/WebMasterLog/assets/168436423/6d3e0dfd-9ade-4150-a1ce-bd1921f3c478">

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

-  [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-06-27 09:27 UTC, Avdhesh-Varshney requested changes

2024-06-27 09:27 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/README.md
> +|	 43 |	[Prime-Number-Checker](./Basic/Prime-Number-Checker/) | ![Basic](https://img.shields.io/badge/Basic-00FF00?style=for-the-badge)
don't disturb the alignment

2024-06-27 15:00 UTC, Anshika14528 commented
@Avdhesh-Varshney sir, i have made the required changes please review it.

2024-06-29 06:34 UTC, Avdhesh-Varshney approved these changes
@Anshika14528 PR Approved 🎉

2024-06-29 06:35 UTC, merged