Added new frontend project Iphone 14 pro clone
Avdhesh-Varshney/WebMasterLog pull request #439
Opened 2024-06-30 12:51 UTC by vansh-codes

Closes: #433 

- **Title** : IPHONE 14 Pro Clone
- **Name:** : Vansh Chaurasiya
- **Idenitfy yourself:** : GSSoC Contributor

### Describe the add-ons or changes you've made 📃
Updated the databaes frontend.json file and added my project tags and description. Updated the frontend folder readme and added my project's link also.
Added files for my project along with a webp screenshot of the clone website.

### How Has This Been Tested? ⚙️

Tested locally

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/392802f2-3a84-4162-a3b3-0608c5876c6e)

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/8a506279-b25c-4203-a044-527d1db5dfa4)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-01 03:42 UTC, Avdhesh-Varshney requested changes
@vansh-codes resolve merge conflicts

2024-07-01 03:42 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/IPHONE-14-Pro-Clone/Screenshot.webp
rename it to `screenshot`

2024-07-01 05:54 UTC, vansh-codes commented on Front-end-Projects/Intermediate/IPHONE-14-Pro-Clone/Screenshot.webp
Resolved. Please check now

2024-07-03 03:45 UTC, Avdhesh-Varshney reviewed
Re-raise your by updating your forked repository.

2024-07-03 03:45 UTC, closed without merging