Animated Tea Cup
Avdhesh-Varshney/WebMasterLog pull request #461
Opened 2024-07-04 11:46 UTC by AmrutaJayanti

Closes: #450 

- **Title** : Animated Tea Cup
- **Name:** : Amruta Jayanti
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃

I have added `Animated-Tea-Cup`

### How Has This Been Tested? ⚙️

Tested it locally

### Screenshots 📷

![Screenshot 2024-07-04 170708](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142327526/55cf8919-ff33-47dc-9472-041c419d2399)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

Please approve

2024-07-05 11:46 UTC, Avdhesh-Varshney requested changes

2024-07-05 11:46 UTC, Avdhesh-Varshney commented on Front-end-Projects/Basic/Animated-Tea-Cup/README.md
> +<!-- directly add the link of video (If, possible) -->
@AmrutaJayanti remove this heading, if video is not present.

2024-07-05 23:09 UTC, AmrutaJayanti commented
@Avdhesh-Varshney I have made the changes. Please approve

2024-07-06 02:52 UTC, Avdhesh-Varshney approved these changes

2024-07-06 02:56 UTC, merged