Added Synonym-Searcher
Avdhesh-Varshney/WebMasterLog pull request #476
Opened 2024-07-06 05:06 UTC by AnshikaAg03

Closes: #452 

- **Title** : Synonym-Searcher
- **Name:** : Anshika
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
 I have added a synonym-searcher.

### How Has This Been Tested? ⚙️

I have tested this in my local computer

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/122719744/e22dbac6-1ab0-4f6f-9ad2-902a01703063)

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-06 05:07 UTC, AnshikaAg03 commented
@Avdhesh-Varshney  please check my pr now , i have made all the requested changes

2024-07-07 14:11 UTC, Avdhesh-Varshney requested changes

2024-07-07 14:11 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Synonym-Searcher/README.md
> +![image](./Synonym-Searcher.webp)
change it and attach `screenshot.webp`

2024-07-07 14:11 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/README.md
> +|  50  | [Synonym-Searcher](./Intermediate/Synonym-Searcher/) | ![Intermediate](https://img.shields.io/badge/Intermediate-FFD700?style=for-the-badge) |
keep it inside the div not outside.

2024-07-07 14:23 UTC, AnshikaAg03 commented
@Avdhesh-Varshney I have made the requested changes please review it now

2024-07-08 18:10 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Synonym-Searcher/README.md
> +![image](./Synonym-Searcher.webp)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/b2cd1b27-6757-4ead-8a30-f4ea544ba86e)

2024-07-08 18:42 UTC, AnshikaAg03 commented
@Avdhesh-Varshney  i have uploaded screenshot.webp now

2024-07-09 03:19 UTC, Avdhesh-Varshney approved these changes

2024-07-09 03:23 UTC, merged