World population project
Avdhesh-Varshney/WebMasterLog pull request #487
Opened 2024-07-07 17:37 UTC by vansh-codes

Closes: #480 

- **Title** : World Population Stats
- **Name:** : Vansh Chaurasiya
- **Idenitfy yourself:** : GSSOC'24 Contributor

### Describe the add-ons or changes you've made 📃
Updated the vanilla sj folder readme and added my project's link also.
Added files for my project along with a webp screenshot of the clone website.

### How Has This Been Tested? ⚙️

Tested locally

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/b7c8dfc9-1f87-4c86-bb59-99039ee396f7)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/df7b9314-5cbe-4ebf-8fc0-4c6d4f8042fe)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/e429c3c8-4426-4936-854c-0ee0de582431)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/5455709f-d9fe-481d-a4ef-b0feaf4671c1)
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114163734/dfa7c711-07cb-4298-8bd6-8d1029a3f2e3)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

Assign under GSSoC'24. 
Thank you!

2024-07-08 18:14 UTC, Avdhesh-Varshney commented
resolve merge conflicts

2024-07-09 08:18 UTC, vansh-codes commented
> resolve merge conflicts

Resolved ✅ 
Please check now @Avdhesh-Varshney

2024-07-10 03:19 UTC, Avdhesh-Varshney requested changes
add a readme file of project explanation

2024-07-10 12:40 UTC, vansh-codes commented
> add a readme file of project explanation

Added ✅

2024-07-11 11:53 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/World-Population/README.md
![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/114330097/d3e55159-8906-4157-bb23-14cd378c677e)
properly write the readme file

2024-07-11 17:19 UTC, closed without merging