Added Apna-College-Clone
Avdhesh-Varshney/WebMasterLog pull request #491
Opened 2024-07-08 06:56 UTC by heli0707

Closes: #466 

- **Title** : Apna-College-Clone
- **Name:** : Heli
- **Idenitfy yourself:** : GSSOC Contributor

### Describe the add-ons or changes you've made 📃
The project added as Apna-College-Clone
The clone project uses HTML, CSS, and JavaScript to create reusable components for better maintainability and scalability. It manages routes for "Home", "New Courses", "Log In", and "Sign Up" pages, and includes forms with basic validation. The design ensures consistency and responsiveness across the webpage.

### How Has This Been Tested? ⚙️
I have tested it on my own.

### Screenshots 📷
![s1](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/6f21d353-dad6-46d8-afd1-39113aa66944)
![s2](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/3fca451c-caf3-4e2c-bf0d-d78a515f98f7)
![s3](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/95361125/84130f51-c052-46f0-b520-d894d5b7cbc2)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-08 07:07 UTC, heli0707 commented
@Avdhesh-Varshney 
Please review it and let me know if there are any problems with it

2024-07-08 18:31 UTC, Avdhesh-Varshney requested changes
@heli0707 enlist your project in the readme file of vanilla js

2024-07-08 18:31 UTC, Avdhesh-Varshney commented on .vscode/settings.json
revoke these changes

2024-07-09 04:22 UTC, heli0707 reviewed
settings.json file updated 
review it!

2024-07-09 04:31 UTC, heli0707 commented
@Avdhesh-Varshney 
listed project in the readme file of vanilla js
could you see that?

2024-07-10 03:23 UTC, Avdhesh-Varshney requested changes

2024-07-10 03:23 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Apna-College-Clone/README.md
> +<h1 align='center'><b>💥 Isogram Checker 💥</b></h1>
carefully write the readme.

2024-07-10 03:46 UTC, heli0707 commented on Vanilla-JS-Projects/Basic/Apna-College-Clone/README.md
> +<h1 align='center'><b>💥 Isogram Checker 💥</b></h1>
done

2024-07-10 03:46 UTC, heli0707 reviewed
@Avdhesh-Varshney 
done all changes

2024-07-10 04:21 UTC, Avdhesh-Varshney approved these changes

2024-07-10 04:22 UTC, merged