Added IP-Address Tracker React js Project
Avdhesh-Varshney/WebMasterLog pull request #516
Opened 2024-07-10 23:13 UTC by Maheshwari-Love

Closes: #498 

- **Title** : IP-Address Tracker
- **Name:** : Maheshwari Love
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃

Added the Ip-address-Tracker Reackjs application

### How Has This Been Tested? ⚙️

I have run it on my local system and have tested.

### Screenshots 📷

![image](https://github.com/Avdhesh-Varshney/WebMasterLog/assets/142833275/0763eada-aabd-43ce-88b5-072ff6ec6a94)

### Type of change ☑️

What sort of change have you made:
Added new project 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-10 23:14 UTC, Maheshwari-Love commented
@Avdhesh-Varshney please review this pR

2024-07-11 13:02 UTC, Avdhesh-Varshney requested changes
follow & read the guidelines properly

2024-07-11 21:46 UTC, Maheshwari-Love commented
> follow & read the guidelines properly

@Avdhesh-Varshney requested changes done

2024-07-12 07:15 UTC, Avdhesh-Varshney requested changes
carefully follow the guidelines. there are some more changes are also left.

2024-07-12 07:15 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/IP-Address-Tracker/README.md
@Maheshwari-Love remove your commented part and fix the ss

![image](https://github.com/user-attachments/assets/c6bc5dae-7414-494e-b11a-cf229bd3d4a2)

2024-07-14 04:39 UTC, Avdhesh-Varshney approved these changes

2024-07-14 04:40 UTC, merged