Countdown Timer using Vanilla JS #17
Avdhesh-Varshney/WebMasterLog pull request #52
Opened 2024-01-25 14:22 UTC by vishal2005025

# Pull Request for WebMasterLog 💡

## Issue Title: Countdown Timer using Vanilla JS

- **Name of the project** : Countdown Timer
- **Category:** : Vanila Js
- **Name:** : Vishal Malyan
- **GitHub ID:** : https://github.com/vishal2005025
- **Idenitfy yourself:** : JWOC'24 Contributer

Closes: #17 

### Describe the add-ons or changes you've made 📃

Created a "Countdown Timer" project using HTML ,CSS and Javascript.

## Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested? ⚙️

I verified my project using live server of vsCode

## Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷

1. <img src='./photo1.webp.webp'>

2. <img src='./photo2.webp.webp'>

3. <img src='./photo3.webp.webp'>

## Note to reviewers 📄

Please review my PR and let me know the feedback..Thank You!

2024-01-26 04:54 UTC, Avdhesh-Varshney requested changes
@vishal2005025 LGTM, resolve these conflicts and again mentioned to me.

2024-01-26 04:54 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Countdown-Timer/README.md
> +  <img width="55" src="https://raw.githubusercontent.com/gilbarbara/logos/master/logos/javascript.svg"/>
Add the standard logo of the JS as i have mentioned.

2024-01-26 04:54 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Countdown-Timer/README.md
> +  <a href='linkedin.com/in/Vishal-malyan'>
Link your linkedin link properly with https as in github url

2024-01-26 04:54 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Countdown-Timer/photo1.webp.webp
Requirement of screenshot is just 1 with the same name as of directory `Countdown-Timer.webp` only webp format not it's name.

2024-01-26 04:54 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Countdown-Timer/README.md
> +1. <img src='./photo1.webp.webp'>
Attach these images by uploading in the comment section and add their links here or you can refer from other project's readme files.

2024-01-26 10:07 UTC, vishal2005025 commented
sir , please review..

2024-01-26 11:35 UTC, Avdhesh-Varshney approved these changes
@vishal2005025 in single commit you can do all these things which i have mentioned. It's not necessary to do commit for each and every deletion and addition. OK

2024-01-26 11:36 UTC, Avdhesh-Varshney commented
@vishal2005025 PR Approved 🎉

2024-01-26 11:36 UTC, merged

2024-01-28 05:51 UTC, vishal2005025 commented
Sir , sorry for the late reply please change the label of this to # hard as I have work hard and I have also add stopwatch and clock to this issue and spent many days to fix it ..
please change please....