Added Garden planning website
Avdhesh-Varshney/WebMasterLog pull request #544
Opened 2024-07-12 10:28 UTC by aditya-bhaumik

Closes: #515 

- **Title** :  Garden Planning Website
- **Name:** :  Aditya Bhaumik
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃
The Garden Planner website is an interactive tool designed for users to create and visualize their ideal garden layout. Users can drag and drop various plants into a grid to plan their garden space while tracking the total cost based on the selected plants. The site allows for saving and loading garden layouts, making it easy to manage and modify designs over time. With a user-friendly interface and responsive design, it aims to enhance the gardening experience for both beginners and enthusiasts.

### How Has This Been Tested? ⚙️

i have checked it in my local machine 

### Screenshots 📷

![image](https://github.com/user-attachments/assets/f4b2ee65-6852-4012-bbdc-677eed3c3598)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-12 10:31 UTC, aditya-bhaumik commented
@Avdhesh-Varshney please review my pull request and merge it 
Sorry for adding 3 commits i forgot to change the readme file

2024-07-14 04:55 UTC, Avdhesh-Varshney requested changes
@aditya-bhaumik resolve merge conflicts

2024-07-14 07:36 UTC, aditya-bhaumik commented
@Avdhesh-Varshney i have resolved the conflicts please review and merge this pull request

2024-07-14 14:10 UTC, Avdhesh-Varshney approved these changes

2024-07-14 14:12 UTC, merged