Added Zomato Clone(frontend)
Avdhesh-Varshney/WebMasterLog pull request #550
Opened 2024-07-14 06:23 UTC by meetarora10

Closes: #521

- **Title** : Add Zomato Clone frontend
- **Name:** : Meet Arora
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
I have added a frontend layout of Zomato clone that is completely responsive with different images and sections and an attractive UI.

### How Has This Been Tested? ⚙️
I have tested it on my own.

### Screenshots 📷

![Screenshot (695)](https://github.com/user-attachments/assets/1c723f13-eb5b-443b-ba17-50319d25fbaf)
![Screenshot (720)](https://github.com/user-attachments/assets/9058c426-5333-482b-999c-83513f5e990e)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-16 02:16 UTC, Avdhesh-Varshney requested changes
resolve merge conflicts

2024-07-16 02:47 UTC, meetarora10 commented
@Avdhesh-Varshney done .

2024-07-18 16:38 UTC, meetarora10 commented
@Avdhesh-Varshney kindly review this .

2024-07-19 05:18 UTC, Avdhesh-Varshney approved these changes

2024-07-19 05:18 UTC, merged