Myntra clone
Avdhesh-Varshney/WebMasterLog pull request #561
Opened 2024-07-16 08:47 UTC by sanayamahajan-23

Closes: 512

- **Title** : Myntra-clone website 
- **Name:** : Sanaya Mahajan
- **Idenitfy yourself:** : GSSOC Contributer

### Describe the add-ons or changes you've made 📃
I have added myntra-clone folder in React-JS Projects in intermediate level

### How Has This Been Tested? ⚙️

I have run on my local computer also checked if there are changes made.

### Screenshots 📷

![Screenshot from 2024-07-16 13-42-59](https://github.com/user-attachments/assets/91db4a58-2bde-4eb8-93d7-e5882e2fc19e)
### Type of change ☑️

What sort of change have you made:
Added a clone of myntra website.
Example how to mark a checkbox:-

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-17 11:19 UTC, sanayamahajan-23 commented
@Avdhesh-Varshney kindly look into my pull request

2024-07-18 06:32 UTC, sanayamahajan-23 commented
@Avdhesh-Varshney please look into my pull request

2024-07-19 05:26 UTC, Avdhesh-Varshney requested changes
update the folder name to `Myntra-Clone`

2024-07-19 05:26 UTC, Avdhesh-Varshney commented on React-JS-Projects/Intermediate/myntra-clone/README.md
> +<h4 align='center'>Developed By <b><i>YOUR NAME</i></b> 👦</h4>
update it

2024-07-19 14:13 UTC, sanayamahajan-23 commented
did the changes as you suggested @Avdhesh-Varshney

2024-07-20 08:49 UTC, sanayamahajan-23 commented
@Avdhesh-Varshney please look into my pull request

2024-07-20 17:22 UTC, Avdhesh-Varshney approved these changes

2024-07-20 17:23 UTC, merged

2024-07-20 17:23 UTC, Avdhesh-Varshney commented
properly link your pr with assigned issue.