Expense Splitter Website
Avdhesh-Varshney/WebMasterLog pull request #569
Opened 2024-07-17 17:00 UTC by vivekvardhan2810

Closes:  #530

- **Title** : Expense Splitter Website
- **Name:** :  Vivek Vardhan
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃

This advanced expense splitter website allows users to input the number of participants, dynamically add their names, and record expenses with details on who paid. It features an option to upload bill images and calculates how much each participant owes or is owed, ensuring all components are responsive and visually appealing.

### How Has This Been Tested? ⚙️

I have Tested This in my local machine

### Screenshots 📷

![Screenshot](https://github.com/user-attachments/assets/6c3bc597-fb4d-486e-b3f8-3121ed252a1e)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-17 17:01 UTC, vivekvardhan2810 commented
@Avdhesh-Varshney Please review and Merge the Pull Request

2024-07-19 05:34 UTC, Avdhesh-Varshney requested changes
resolve merge conflicts

2024-07-19 05:34 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Expense-Splitter-Website/Screenshot.webp
It's `screenshot` not `Screenshot`

2024-07-19 16:04 UTC, vivekvardhan2810 commented
@Avdhesh-Varshney I have made the changes requested

2024-07-20 17:27 UTC, Avdhesh-Varshney approved these changes

2024-07-20 17:27 UTC, merged