Added password manager
Avdhesh-Varshney/WebMasterLog pull request #580
Opened 2024-07-19 06:53 UTC by thevijayshankersharma

Closes: #562 

- **Title** :  Password Manager
- **Name:** : Vijay Shanker Sharma
- **Idenitfy yourself:** : GSSOC

I added ```Password Manager```

### How Has This Been Tested? ⚙️

I tested it locally

### Screenshots 📷

![image](https://github.com/user-attachments/assets/f4accc5a-96ac-4a82-bbb7-e04a669988db)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-22 04:04 UTC, Avdhesh-Varshney requested changes
Properly follow and read the guidelines

2024-07-22 11:41 UTC, thevijayshankersharma commented
@Avdhesh-Varshney Is it correct now ??

2024-07-26 01:48 UTC, thevijayshankersharma commented
@Avdhesh-Varshney , is it correct now? If there are any other issues, please specify what needs to be done more specifically.

2024-07-26 02:44 UTC, meetarora10 commented
@thevijayshankersharma you have to enter your project in other README file .

2024-07-26 09:53 UTC, thevijayshankersharma commented
@Avdhesh-Varshney @meetarora10 Done.

2024-07-27 04:39 UTC, Avdhesh-Varshney requested changes

2024-07-27 04:39 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Password-Manager/image.png
change this ss from png to webp format. Name of ss file is `screenshot`

2024-07-27 06:28 UTC, thevijayshankersharma commented on Vanilla-JS-Projects/Basic/Password-Manager/image.png
Sure.

2024-07-27 12:06 UTC, thevijayshankersharma commented on Vanilla-JS-Projects/Basic/Password-Manager/image.png
@Avdhesh-Varshney Done. Could you check my others issues too.

2024-07-28 06:03 UTC, Avdhesh-Varshney requested changes

2024-07-28 06:03 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +![Screenshot](./image.png)
.

2024-07-28 06:03 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +  <a href='https://www.linkedin.com/in/your-linkedin-profile/'>
.

2024-07-28 06:03 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +  <a href='https://github.com/your-github-profile'>
.

2024-07-28 10:04 UTC, thevijayshankersharma commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +![Screenshot](./image.png)
I will do this.

2024-07-28 10:04 UTC, thevijayshankersharma commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +  <a href='https://www.linkedin.com/in/your-linkedin-profile/'>
what is wrong in this ?

2024-07-28 10:04 UTC, thevijayshankersharma commented on Vanilla-JS-Projects/Basic/Password-Manager/README.md
> +  <a href='https://github.com/your-github-profile'>
what is wrong in this ?

2024-07-28 10:09 UTC, thevijayshankersharma commented
@Avdhesh-Varshney Done

2024-07-29 03:31 UTC, Avdhesh-Varshney approved these changes
Please fill this survey form https://forms.gle/Wvsp9N8TDF1WPStq9

2024-07-29 03:32 UTC, merged