Added Recipe book
Avdhesh-Varshney/WebMasterLog pull request #610
Opened 2024-07-21 16:15 UTC by pavitraag

Closes: #598 

- **Title** :  Recipe Book
- **Name:** : Pavitraa
- **Idenitfy yourself:** : GSSOC contributor 

### Screenshots 📷
<img width="920" alt="image" src="https://github.com/user-attachments/assets/32e2514d-be00-4211-a9cc-f3e424575fa6">

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

2024-07-22 03:47 UTC, Avdhesh-Varshney requested changes
Also read & follow the guidelines properly.

2024-07-22 03:47 UTC, Avdhesh-Varshney commented on Front-end-Projects/Basic/Recipe book/Readme.md
properly fill the readme template

2024-07-22 09:21 UTC, pavitraag commented
@Avdhesh-Varshney done with changes

2024-08-03 05:26 UTC, Avdhesh-Varshney commented
Add a ss with format `webp` and named to be `screenshot`

2024-08-04 02:23 UTC, pavitraag commented
@Avdhesh-Varshney done

2024-08-04 14:12 UTC, Avdhesh-Varshney commented
Re-raise this pr. Closed because only due to 13 numbers of commits.

2024-08-04 14:12 UTC, closed without merging