Nodemailer Mail sender
Avdhesh-Varshney/WebMasterLog pull request #619
Opened 2024-07-22 16:49 UTC by dhairyagothi

Closes: 

- **Title** :  Nodemailer
- **Name:** :  Dhairya gothi
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃

### How Has This Been Tested? ⚙️

### Screenshots 📷

![Uploading Screenshot 2024-07-20 155527.png…]()

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-23 03:28 UTC, dhairyagothi commented
@Avdhesh-Varshney sir please merge PR

2024-07-23 03:40 UTC, Avdhesh-Varshney commented
Properly follow the instructions. I'm not told to anyone again & again.

2024-07-23 03:56 UTC, dhairyagothi commented
Done @Avdhesh-Varshney

2024-07-24 03:57 UTC, Avdhesh-Varshney requested changes

2024-07-24 03:57 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Intermediate/Gmail-Nodemailer/readme.md
> + ![alt text](image.png)
review it

2024-07-24 04:49 UTC, dhairyagothi commented
@Avdhesh-Varshney please tell anything else i need to change ?

2024-07-24 04:49 UTC, dhairyagothi commented on Node-JS-Projects/Intermediate/Gmail-Nodemailer/readme.md
> + ![alt text](image.png)
resolved

2024-07-28 05:51 UTC, dhairyagothi commented
@Avdhesh-Varshney please merge PR 31 july is last date for contributing PR

2024-07-28 06:06 UTC, Avdhesh-Varshney requested changes
Enlist your project in readme file

2024-07-28 07:04 UTC, dhairyagothi commented
done @Avdhesh-Varshney

2024-07-29 03:34 UTC, Avdhesh-Varshney approved these changes
Please fill this survey form https://forms.gle/Wvsp9N8TDF1WPStq9

2024-07-29 03:34 UTC, merged