added expense tracker in vuejs
Avdhesh-Varshney/WebMasterLog pull request #620
Opened 2024-07-22 17:14 UTC by Maheshwari-Love

Closes: 

- **Title** : Expense Tracker
- **Name:** :  Maheshwari Love
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃
Adde new project expense tracker in Vuejs 

### How Has This Been Tested? ⚙️

I have manually run the project on my local system

### Screenshots 📷

![image](https://github.com/user-attachments/assets/b014f91f-e54e-4131-a3fc-31cf83105b1a)

### Type of change ☑️

What sort of change have you made:
added new project

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-24 02:24 UTC, Maheshwari-Love commented
@Avdhesh-Varshney please review this pr

2024-07-24 10:45 UTC, Maheshwari-Love commented
@Avdhesh-Varshney   i have followed the guidlines. Can you please specify the requested changes

2024-07-25 05:47 UTC, Avdhesh-Varshney requested changes

2024-07-25 05:47 UTC, Avdhesh-Varshney commented on Vue-JS-Projects/README.md
> +|   3   | [Expense Tracker](./Intermediate/Expense-Tracker/) | ![Basic](https://img.shields.io/badge/Basic-00FF00?style=for-the-badge) |
Attach the label of Intermediate

2024-07-27 04:01 UTC, Avdhesh-Varshney approved these changes

2024-07-27 04:01 UTC, merged

2024-07-27 04:02 UTC, Avdhesh-Varshney commented
Properly link your issue with the pr. And also carefully attach the label in readme file.

@Maheshwari-Love Please fill the feedback form: https://forms.gle/Wvsp9N8TDF1WPStq9

2024-07-27 04:04 UTC, Maheshwari-Love commented
> Properly link your issue with the pr. And also carefully attach the label in readme file.
> 
> @Maheshwari-Love Please fill the feedback form: https://forms.gle/Wvsp9N8TDF1WPStq9

okay i will take care of that