3D Solar-System
Avdhesh-Varshney/WebMasterLog pull request #621
Opened 2024-07-22 18:01 UTC by Damini2004

Closes: #435 

- **Title** : 3D Solar-System
- **Name:** : Damini Chachane
- **Idenitfy yourself:** : GSSOC

### Describe the add-ons or changes you've made 📃

### How Has This Been Tested? ⚙️

### Screenshots 📷
![Screenshot 2024-07-22 231222](https://github.com/user-attachments/assets/4ec03b0f-64f4-461d-87b9-ff9d03e4d2e9)

### Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-23 03:37 UTC, Avdhesh-Varshney requested changes
Can you attach a working video?
And keep it inside Vanilla JS folder.

2024-07-23 05:02 UTC, Damini2004 commented
https://github.com/user-attachments/assets/25372bd2-2374-41ba-8f57-5b1ffce125de

2024-07-23 05:02 UTC, Damini2004 commented
Can you increase the level.

2024-07-24 04:02 UTC, Avdhesh-Varshney approved these changes

2024-07-24 04:03 UTC, merged