Added Job Portal Project
Avdhesh-Varshney/WebMasterLog pull request #668
Opened 2024-07-26 19:29 UTC by abckhush

Closes: #595 

- **Title** :  ReactJS Project: Job Portal
- **Name:** : Khushi Kalra
- **Idenitfy yourself:** : GSSOC'24

### Describe the add-ons or changes you've made 📃
Added an advanced ReactJS Project: Job Portal which helps users apply to various jobs and find suitable employment.

### How Has This Been Tested? ⚙️
The application was manually tested by navigating through all the pages, performing searches, and verifying the accuracy of search results.

### Screenshots 📷

![screenshot webp](https://github.com/user-attachments/assets/0f577a0d-5bba-4a1b-a877-3602c352d003)
![Screenshot 2024-07-27 005108](https://github.com/user-attachments/assets/ac1f3068-1c55-4d70-a591-b23ba6c8e629)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

2024-07-28 08:53 UTC, abckhush commented
@Avdhesh-Varshney All issues have been resolved. Kindly merge this.

2024-07-29 03:57 UTC, abckhush commented
@Avdhesh-Varshney Kindly merge this.

2024-07-30 14:27 UTC, Avdhesh-Varshney requested changes

2024-07-30 14:27 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/Job-Portal/screenshot.webp.png
It should be in webp format not in png format.

2024-07-30 14:49 UTC, abckhush commented
@Avdhesh-Varshney Kindly check now :)

2024-08-01 18:45 UTC, Avdhesh-Varshney commented on React-JS-Projects/Advanced/Job-Portal/README.md
> +<h4 align='center'>Developed By <b><i>YOUR NAME</i></b> 👦</h4>
Kindly raise this pr again. Because of large sequence of commit history.

2024-08-01 18:45 UTC, closed without merging