added Breaking news app
Avdhesh-Varshney/WebMasterLog pull request #681
Opened 2024-07-28 04:55 UTC by Maheshwari-Love

Closes: 

- **Title** : Breaking news app
- **Name:** :  Maheshwari Love
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃
Added new project

### How Has This Been Tested? ⚙️

Just added new project in Nextjs technology

### Screenshots 📷

![Screenshot 2024-07-25 165254](https://github.com/user-attachments/assets/362fe5b5-e5f3-43ea-b6a6-008b4c0f62eb)

### Type of change ☑️

added new project 
What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-07-28 04:57 UTC, Maheshwari-Love commented
@Avdhesh-Varshney please review this pr

2024-07-28 06:51 UTC, Avdhesh-Varshney requested changes
Create a directory `Advanced` and keep your project inside in it.

2024-07-28 06:51 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Intermediate/Breaking-News-App/assets/images/newsarticle_placeholder.jpg
reduce the size of file or use any other format of image.

2024-07-28 10:03 UTC, Maheshwari-Love commented
@Avdhesh-Varshney i will raise the pr again

2024-07-28 19:25 UTC, Maheshwari-Love commented
@Avdhesh-Varshney all changes done...

2024-07-29 04:05 UTC, Avdhesh-Varshney approved these changes

2024-07-29 04:06 UTC, merged

2024-07-29 04:06 UTC, Avdhesh-Varshney commented
Please fill this survey form https://forms.gle/Wvsp9N8TDF1WPStq9