Quiz Application using Typescript
Avdhesh-Varshney/WebMasterLog pull request #695
Opened 2024-07-29 18:57 UTC by Madhavan112

Closes: #682

- **Title:** Quiz Application using Typescript
- **Name**: Madhavan V
- **Idenitfy yourself**: GSSOC24

### Describe the add-ons or changes you've made 📃
This is a quiz web application made up of React and Typescript.

### How Has This Been Tested? ⚙️
This application has been tested locally and browser compatibility was too checked

### Screenshots 📷

![screenshot](https://github.com/user-attachments/assets/0c05259f-0a29-4698-944f-2ba37968de3b)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

2024-07-30 13:28 UTC, Avdhesh-Varshney requested changes

2024-07-30 13:28 UTC, Avdhesh-Varshney commented on React-JS-Projects/Basic/Swiggy-Clone/src/App.css
un-necessary changes

2024-07-30 13:53 UTC, Madhavan112 commented
Can you review this quickly ?

2024-08-01 18:53 UTC, Avdhesh-Varshney approved these changes

2024-08-01 18:53 UTC, merged