Amazon-Ecommerce-clone
Avdhesh-Varshney/WebMasterLog pull request #700
Opened 2024-07-30 09:39 UTC by SCR01

Title: Add a Beginner-Friendly E-Commerce Front-End Project.
Closes: #590

Name: Sharad Chandra Reddy

Identify yourself: GSSOC'24

Describe the add-ons or changes you've made 📃

⭐Added assets and files for the project

⭐Added project folder in the readme

How Has This Been Tested? ⚙️

Tested locally

Screenshots 📷
![Screenshot 2024-07-30 142838](https://github.com/user-attachments/assets/913b741d-ea4e-40f4-954d-e9756c4f7b11)

Type of change ☑️

What sort of change have you made:

[✔️] New feature (non-breaking change which adds functionality)

 
Checklist: ☑️

[✔️] My code follows the Contributing Guidelines & Code of Conduct of this project.
 
[✔️] This PR does not contain plagiarized content.
 
  [✔️] I have performed a self-review of my own code.
 
[✔️] I have commented on my code, particularly wherever it was hard to understand.
 
[✔️] My changes generate no new warnings.
 
Note to reviewers 📄

2024-07-30 13:36 UTC, Avdhesh-Varshney requested changes
Carefully follow the guidelines.

2024-07-30 13:36 UTC, Avdhesh-Varshney commented on .hintrc
Delete it or keep it inside your project directory.

2024-07-30 16:32 UTC, SCR01 commented
@Avdhesh-Varshney Please, Review this PR.

2024-08-09 11:27 UTC, Avdhesh-Varshney requested changes
- Naming convention of project folder as written in guidelines. `Amazon-E-Commerce-Clone`
- Add 1 ss just inside the project folder. `screenshot.webp` in webp format.
- Keep your other images inside the `assets` folder.
- And Keep your project in the `Vanilla-JS-Projects` directory ok.

2024-08-10 15:55 UTC, SCR01 commented
@Avdhesh-Varshney I did all the changes as you have mentioned, please merge it.

2024-10-02 07:01 UTC, closed without merging