Added Url-shortener
Avdhesh-Varshney/WebMasterLog pull request #711
Opened 2024-08-01 05:58 UTC by Aditijainnn

Closes: 

- **Title** : Url shortener
- **Name:** :  Aditi Jain
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃
Added url shortener in next js project

### Screenshots 📷

![image](https://github.com/user-attachments/assets/4401d7ee-ec91-4afe-8a89-5717c1d7fdc9)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

2024-08-08 06:10 UTC, Aditijainnn commented
@Avdhesh-Varshney  please merge my pr

2024-08-09 11:30 UTC, Avdhesh-Varshney requested changes
You've not linked your issue with pr.

2024-08-09 11:30 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Intermediate/Url-Shortener/Screenshot.webp.png
It should be in `webp` format and named as `screenshot` => `screenshot.webp` ok

2024-08-09 11:30 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Intermediate/Url-Shortener/README.md
> +<img src="./screenshot.webp.png"/>
Don't forget to update it.

2024-08-09 12:32 UTC, closed without merging