Rental
Avdhesh-Varshney/WebMasterLog pull request #712
Opened 2024-08-01 06:29 UTC by Aditijainnn

Closes: 
 #579

- **Title** : property rental website
- **Name:** :  Aditi
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃

### How Has This Been Tested? ⚙️

### Screenshots 📷

![image](https://github.com/user-attachments/assets/2ab16ac4-64b6-4911-9e8f-7b4a1b910969)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

2024-08-02 14:26 UTC, Avdhesh-Varshney commented
Review your pr by your own and follow the guidelines carefully.

2024-08-03 09:35 UTC, Aditijainnn commented
> Review your pr by your own and follow the guidelines carefully.

yes reviewed

2024-08-08 06:11 UTC, Aditijainnn commented
@Avdhesh-Varshney please merge my pr

2024-08-09 11:35 UTC, Avdhesh-Varshney requested changes
You've committed your earlier project also in this project.
Either delete the un-necessary project or closed this pr.

2024-08-09 11:35 UTC, Avdhesh-Varshney commented on Typescript-Projects/Advanced/Rental-Website/README.md
> +<img src='./Countdown-Timer.webp'>
Where is this image?
- You've to follow the guidelines of ss as mentioned in your earlier pr.

2024-08-09 12:50 UTC, closed without merging