Added image to text project
Avdhesh-Varshney/WebMasterLog pull request #717
Opened 2024-08-01 17:51 UTC by Utsavladia

Closes: 

- **Title** :  Image to text project
- **Name:** : Utsav Ladia
- **Idenitfy yourself:** :  GSSOC

### Describe the add-ons or changes you've made 📃

### How Has This Been Tested? ⚙️

### Screenshots 📷
![image](https://github.com/user-attachments/assets/3354a254-e057-4dcc-9281-97bca9f640fa)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-08-02 14:28 UTC, Avdhesh-Varshney commented
Can you review your pr? And where is your project?

2024-08-02 15:58 UTC, Utsavladia commented
@Avdhesh-Varshney 
I fixed the project section previously it got added as submodule

2024-08-04 18:15 UTC, Utsavladia commented
@Avdhesh-Varshney 
Is this alright to be merged?

2024-08-08 04:43 UTC, Utsavladia commented
@Avdhesh-Varshney kindly reivew this gssoc is getting ended

2024-08-08 11:12 UTC, Utsavladia commented
@Avdhesh-Varshney 
Kindly merge this PR before closing of GSSOC 🙂

2024-08-09 11:37 UTC, Avdhesh-Varshney requested changes
Carefully follow the guidelines of project is, `Text-To-Image` ok.

2024-08-09 11:37 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Intermediate/text-to-image/README.md
- Follow the readme template.
- Add ss file with provide file conventions in guidelines.

2024-08-09 11:38 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Intermediate/text-to-image/README.md
Also enlist your project in Next-JS-Projects readme file.

2024-10-02 07:00 UTC, closed without merging