Added Amazon Clone Frontend
Avdhesh-Varshney/WebMasterLog pull request #725
Opened 2024-08-02 16:08 UTC by shellygarg10

Closes: 

- **Title** :  Amazon Clone Frontend
- **Name:** :  Shelly Garg
- **Idenitfy yourself:** :  GSSOC 24

### Describe the add-ons or changes you've made 📃
Added a project made using basics of HTML and CSS.

### How Has This Been Tested? ⚙️

### Screenshots 📷

![image](https://github.com/user-attachments/assets/664675e9-c966-4a9a-9cc7-d22d2534f365)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-08-03 05:11 UTC, shellygarg10 commented
@Avdhesh-Varshney can you please explain the issues to me

2024-08-04 13:04 UTC, shellygarg10 commented
@Avdhesh-Varshney i made corrections and followed all the guidelines correctly now , please review my pr once again

2024-08-04 14:16 UTC, Avdhesh-Varshney requested changes

2024-08-04 14:16 UTC, Avdhesh-Varshney commented on Front-end-Projects/Basic/Amazon-Clone/Amazon_clone.png
convert it into `webp` format and rename it to `screenshot`.

2024-08-04 14:16 UTC, Avdhesh-Varshney commented on Front-end-Projects/README.md
> +|   23  | [Amazon Clone](./Basic//Amazon_clone) | ![Basic](https://img.shields.io/badge/Basic-00FF00?style=for-the-badge) |
Correct here also.

2024-08-04 14:16 UTC, Avdhesh-Varshney commented on Front-end-Projects/Basic/Amazon-Clone/Amazon_clone.png
Don't forget to correct your image in your project readme file.

2024-10-02 06:59 UTC, closed without merging