Add: attendance-track-nextjs-app
Avdhesh-Varshney/WebMasterLog pull request #757
Opened 2024-08-07 22:54 UTC by anisharma07

Closes:  #317

- **Title** :  Attendance Tracker
- **Name:** :  Anirudh Sharma
- **Idenitfy yourself:** : GSSOC'24 Contributor

### Describe the add-ons or changes you've made 📃
Added the Project folder to the Nextjs/advanced folder
updated nextjs/ README.md

### How Has This Been Tested? ⚙️
-> The app has been tested both on mobile and computer under different situations and taking different values
-> Detailed working video of web app is attached.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/3a513bac-63da-4c99-ae48-4ea183713126)

![image](https://github.com/user-attachments/assets/d2e06947-324c-4f76-a3f6-b362e41255cd)

https://github.com/user-attachments/assets/c15f3199-d656-4c38-b64d-0251a2ddd400

### Type of change ☑️

- [x] My code follows the code style of this project.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
Please assign under Gssoc'24 & mark appropriate labels ....... a level 3 label would be helpful (created whole app from scratch from UI designing to building backend)

2024-08-08 13:50 UTC, Avdhesh-Varshney requested changes

2024-08-08 13:50 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Advanced/Attendance-Tracking-App/README.md
Follow the readme template and attach 1 file of screenshot in `webp` format and named it to `screenshot` i.e. `screenshot.webp`

2024-08-08 13:50 UTC, Avdhesh-Varshney commented on Next-JS-Projects/README.md
Don't update any other thing else enlisting your project here.

2024-08-08 18:48 UTC, anisharma07 commented on Next-JS-Projects/Advanced/Attendance-Tracking-App/README.md
done updating the readme file & adding screenshot.webp

2024-08-08 18:49 UTC, anisharma07 commented on Next-JS-Projects/README.md
project is updated in the list

2024-08-08 18:50 UTC, anisharma07 commented
@Avdhesh-Varshney 
Done updating readme & adding screenshot & updated the projects list

2024-08-09 08:03 UTC, anisharma07 commented
@Avdhesh-Varshney 
Please review the Changes ... today is last date for Gssoc'24

2024-08-09 11:55 UTC, Avdhesh-Varshney requested changes

2024-08-09 11:55 UTC, Avdhesh-Varshney commented on Next-JS-Projects/README.md
Remoke your un-necessary changes.

2024-08-09 17:12 UTC, anisharma07 commented
@Avdhesh-Varshney 
Please review the PR

2024-08-10 11:04 UTC, Avdhesh-Varshney approved these changes

2024-08-10 11:05 UTC, merged