added crypto-dashboard
Avdhesh-Varshney/WebMasterLog pull request #790
Opened 2024-10-04 10:38 UTC by Aditijainnn

Closes: #785

- **Title:** Crypto Dasboard
- **Name:** Aditi
- **Idenitfy yourself:**  Gssoc ext and Hacktoberfest 2024

### Screenshots 📷

![372829766-e21ec12f-da3b-4917-8a6e-0a9a71d378c8](https://github.com/user-attachments/assets/af356ea1-1b6a-4071-94db-70a18dc196b2)

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
-->
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

2024-10-06 10:13 UTC, Avdhesh-Varshney requested changes

2024-10-06 10:13 UTC, Avdhesh-Varshney commented on Vue-JS-Projects/Intermediate/Crypto-Dashboard/README.md
> +<img src='./screenshot.webp.png'>
There is a mis-understanding. You have to convert your png file into webp format. That's why guidelines says `screenshot.webp` not `screenshot.png` and not `screenshot.webp.png`.

2024-10-06 10:17 UTC, Avdhesh-Varshney commented
https://github.com/JayeshLab/vue-crypto-dashboard

2024-10-06 10:17 UTC, closed without merging

2024-10-16 12:34 UTC, Aditijainnn commented
@Avdhesh-Varshney please can you remove the spam tag because due to this got disqualied from hacktoberfest 
please i will not repeat this again can you remove spam tag

2024-10-17 18:05 UTC, Aditijainnn commented
> Don't repeat it next time

OK thank you sir