Added Google Search Clone
Avdhesh-Varshney/WebMasterLog pull request #822
Opened 2024-10-08 13:39 UTC by nksmanya

Closes: #817 

- **Title:** Google Search Clone 
- **Name:** Manya .N
- **GSSoc'24 extd, Hacktoberfest Contributor**

### Describe the add-ons or changes you've made 📃
I have added the Google Search, Google Image search and Google Advanced Search Clone

### Screenshots 📷
Google Search:
![image](https://github.com/user-attachments/assets/d0967d33-9c0e-42f3-b6c6-c8e21eb90cf2)

Google Image Search:
![image](https://github.com/user-attachments/assets/7caafc26-2ec2-4fa3-8615-296f60c603b6)

Google Advanced Search:
![image](https://github.com/user-attachments/assets/64c48ef4-7ce3-4098-a291-bd94fb74f9da)

### Type of change ☑️
The Google Search clone can do a Search like the Google Search Engine.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.

### Note to reviewers 📄
Please let me know if there is any issues related to this pull request. 
Aslo please assign the respective labels.

2024-10-09 16:51 UTC, Avdhesh-Varshney requested changes
Add a readme file and 1 `screenshot.webp` file in your project folder.

2024-10-10 00:31 UTC, nksmanya commented
@Avdhesh-Varshney Added README.md and screenshot.webp. 
Please check it.

2024-10-10 11:30 UTC, Avdhesh-Varshney approved these changes

2024-10-10 11:31 UTC, merged

2024-10-10 11:32 UTC, Avdhesh-Varshney commented
Never commit your pr in main branch