Added Qr code generator
Avdhesh-Varshney/WebMasterLog pull request #847
Opened 2024-10-10 15:14 UTC by ananyag309

Closes: #813

- **Title:** Add QR generator
- **Name:** Ananya gupta
- **Idenitfy yourself:**  gssoc ext and hacktoberfest

### Describe the add-ons or changes you've made 📃

### Screenshots 📷

![Uploading Capture.PNG…]()

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ ] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-10 17:28 UTC, Avdhesh-Varshney requested changes

2024-10-10 17:28 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Qr-Code-Generator/README.MD
> +    <p>An analog clock made with HTML, CSS, and JavaScript visually represents time using a traditional clock face with rotating hour, minute, and second hands. It showcases seamless integration of w
Correct it.

2024-10-10 17:28 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Qr-Code-Generator/index.html
> +	</script>
Format the code properly

2024-10-10 17:59 UTC, ananyag309 commented
@Avdhesh-Varshney made all the changes

2024-10-11 04:26 UTC, Avdhesh-Varshney approved these changes

2024-10-11 04:26 UTC, merged