Added Calendar App
Avdhesh-Varshney/WebMasterLog pull request #851
Opened 2024-10-11 06:00 UTC by shalini-bhandari

Closes: #830 

- **Title:**  Calendar App
- **Name:** Shalini Bhandari
- **Idenitfy yourself:**  gssoc-ext, hacktoberfest

### Describe the add-ons or changes you've made 📃

### Screenshots 📷

<img width="1280" alt="Screenshot 2024-10-11 at 11 09 17" src="https://github.com/user-attachments/assets/0d2ae13b-f10d-4140-b49f-0ffd4f002c81">

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [ x My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

2024-10-11 06:02 UTC, shalini-bhandari commented
@Avdhesh-Varshney kindly review it and let me know if any changes are to be made

2024-10-12 09:55 UTC, Avdhesh-Varshney requested changes
Keep your project in `Vanilla-JS-Projects/Intermediate`.

2024-10-12 10:00 UTC, shalini-bhandari commented
@Avdhesh-Varshney kindly review it again. 
Regards

2024-10-20 06:16 UTC, Avdhesh-Varshney requested changes

2024-10-20 06:16 UTC, Avdhesh-Varshney commented on Front-end-Projects/README.md
Undo this project listing from here.
Enlist your project in Vanilla js readme file

2024-10-21 08:07 UTC, Avdhesh-Varshney approved these changes

2024-10-21 08:07 UTC, merged