Create a Paytm landing page clone
Avdhesh-Varshney/WebMasterLog pull request #855
Opened 2024-10-11 07:44 UTC by amanver45

issue #840 
Closes: 

- **Title:** Create a Paytm landing page clone
- **Name:** Aman Verma
- **Idenitfy yourself:**  GSSOC, SSOC, JWOC, etc. Contributor

### Describe the add-ons or changes you've made 📃
Create a Paytm landing page clone

### video

https://github.com/user-attachments/assets/aebdd149-7aa3-4d36-9533-c4764753d39b

- [x] My code follows the code style of this project.
- [x] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the code style of this project.
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

2024-10-11 07:46 UTC, amanver45 commented
@Avdhesh-Varshney I think this is level 2 issue  pls check the project  and reconsider it.

2024-10-12 10:08 UTC, Avdhesh-Varshney requested changes
Review the guidelines properly

2024-10-12 10:08 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Basic/Paytm Clone/readme.md
Update it carefully and rename ss file

2024-10-12 16:25 UTC, amanver45 commented on Vanilla-JS-Projects/Basic/Paytm Clone/readme.md
Done

2024-10-12 16:27 UTC, amanver45 commented
Changes are done

2024-10-13 16:46 UTC, Avdhesh-Varshney requested changes
Folder name to be `Paytm-Clone`
Enlist your project in readme file.

2024-10-13 16:59 UTC, amanver45 commented
@Avdhesh-Varshney all changes are done check it

2024-10-18 10:11 UTC, closed without merging