Added N-Queen Visualizer | Issue #825
Avdhesh-Varshney/WebMasterLog pull request #880
Opened 2024-10-12 16:25 UTC by Shariq2003

Closes: #825 

- **Title:**  N-Queen Visualizer
- **Name:** Shariq
- **Idenitfy yourself:** 
GSSOC Ext

### Describe the add-ons or changes you've made 📃
Added N-Queen Visualizer, a project of Backtracking that help to understand the N-Queen Problem by the Viusualization of it.

### Screenshots 📷

https://github.com/user-attachments/assets/ec940492-7f24-43c7-bd8b-b13459a55b13

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

2024-10-13 20:48 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review

2024-10-14 11:36 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review this PR,

2024-10-15 09:00 UTC, Avdhesh-Varshney requested changes

2024-10-15 09:00 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Advanced/N-Queen-Visualizer/README.md
Follow the project README template.

2024-10-15 09:00 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/README.md
![image](https://github.com/user-attachments/assets/726a1f4f-3f4b-4e4b-ab5a-cd7fba17a283)
Add your project in row 4 not create row 5

2024-10-15 09:07 UTC, Shariq2003 commented
@Avdhesh-Varshney please check

2024-10-15 10:01 UTC, Shariq2003 commented
@Avdhesh-Varshney sir ,please review now

2024-10-15 10:27 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, now i have reviewed all the changes and make the PR ready to merge.
Please review

2024-10-15 16:18 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, could u please merge the PR in order they are creating in time, as I have creates this PR which has no conflicts now, but if u merge a PR that has raise after me, then there will be conflicts in my PR in readme.md file.

So please merge this

2024-10-16 13:09 UTC, Avdhesh-Varshney approved these changes
This time, I've done changes. Review them by your own so that next time. It will not repeat.

2024-10-16 13:09 UTC, merged

2024-10-25 17:29 UTC, NEGRAH-S commented
@MastanSayyad , Only Project addition cannot allow Level 3

2024-10-27 01:56 UTC, MastanSayyad reviewed
@Avdhesh-Varshney reduce to `level 2`

2024-10-27 07:17 UTC, Shariq2003 commented
> @Avdhesh-Varshney reduce to `level 2`

Agreed