Razorpay clone Addition | Issue #826
Avdhesh-Varshney/WebMasterLog pull request #881
Opened 2024-10-12 16:40 UTC by Shariq2003

Closes: #826 

- **Title:** Razorpay Clone Addition 
- **Name:** Shariq
- **Idenitfy yourself:** 
GSSOC Ext
### Describe the add-ons or changes you've made 📃

### Screenshots 📷

![image](https://github.com/user-attachments/assets/e60bfd27-b8f9-40d8-a0a6-1c9d6574225f)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

2024-10-13 21:04 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review

1. I have readme of project to include images and videos
2. Update Readme of Frontend Projects
3. Follow Cabab Casing.

2024-10-14 11:42 UTC, Shariq2003 commented
@Avdhesh-Varshney please review this

2024-10-15 09:03 UTC, Avdhesh-Varshney requested changes

2024-10-15 09:03 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Razorpay-Clone/README.md
https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/PROJECT-README-TEMPLATE.md

2024-10-15 09:03 UTC, Avdhesh-Varshney commented on Front-end-Projects/README.md
Update it in row 5

2024-10-15 09:14 UTC, Shariq2003 commented
@Avdhesh-Varshney please check now

2024-10-15 10:01 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, review now

2024-10-15 10:26 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, Now i have reviewed all the changes and make the PR ready to merge.
Please review this

2024-10-15 16:19 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, could u please merge the PR in order they are creating in time, as I have created this PR which has no conflicts now, but if u merge a PR that has raised after me, then there will be conflicts in my PR in readme.md file.

So please merge this

2024-10-20 06:21 UTC, Avdhesh-Varshney requested changes

2024-10-20 06:21 UTC, Avdhesh-Varshney commented on Front-end-Projects/Intermediate/Razorpay-Clone/Working Video.mp4
Delete it not required.

2024-10-20 09:32 UTC, closed without merging