url-scraper
Avdhesh-Varshney/WebMasterLog pull request #89
Opened 2024-02-14 10:32 UTC by Anushkabh

# Pull Request for WebMasterLog 💡

## Issue Title: #49 
 URL Scraper using Node JS

- **Name of the project** :  URL-Scraper
- **Category:** NodeJS
- **Name:** Anushka
- **GitHub ID:** Anushkabh
- **Idenitfy yourself:** JWOC contributor

Closes: 
 #49 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested postman
Describe how have you verified the changes made

## Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots 📷

## Note to reviewers 📄

2024-02-14 10:34 UTC, Anushkabh commented
@Avdhesh-Varshney  kindly review the pr

2024-02-14 14:26 UTC, Avdhesh-Varshney requested changes
- Follow the contributing guidelines carefully.
- Include a working video and from how to start the application upto interaction.

2024-02-14 14:26 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Intermediate/URL-Scrapper/README.md
Follow the repo README template

2024-02-14 14:29 UTC, Avdhesh-Varshney commented
@Anushkabh resolve these changes and you should properly linked your issue with pr

2024-02-19 06:56 UTC, Avdhesh-Varshney commented
@Anushkabh this pr is commited in the main branch which is totally a wrong way. You should read the contributing guidelines carefully and again create the pull request OK.

2024-02-19 06:56 UTC, closed without merging

2024-02-19 07:26 UTC, Anushkabh commented
@Avdhesh-Varshney apologies for this..