Added Recipe Sharing project
Avdhesh-Varshney/WebMasterLog pull request #909
Opened 2024-10-15 02:04 UTC by mehul-m-prajapati

Closes: #864

- **Title:**  Recipe Sharing project
- **Name:** Mehul P
- **Idenitfy yourself:**  GSSOC

### Describe the add-ons or changes you've made 📃
Added Recipe Sharing project

### Screenshots 📷
![Animation2](https://github.com/user-attachments/assets/831e86c3-130a-4aba-88ee-dccde98224c1)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄
na

2024-10-15 09:23 UTC, Avdhesh-Varshney requested changes
Keep it in Intermediate directory and update the enlisted readme also.

2024-10-15 09:23 UTC, Avdhesh-Varshney commented on Angular-JS-Projects/Advanced/Recipe-Sharing/README.md
Follow the readme template. Alignment is distorted.

2024-10-15 15:39 UTC, mehul-m-prajapati commented on Angular-JS-Projects/Advanced/Recipe-Sharing/README.md
@Avdhesh-Varshney : okay updated readme and moved project to Intermediate

2024-10-16 13:26 UTC, Avdhesh-Varshney reviewed
Have you build this on your own or copied from somewhere, just for contribution?

2024-10-16 13:26 UTC, Avdhesh-Varshney commented on Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/.gitkeep
What's the use of this file?

2024-10-16 13:31 UTC, mehul-m-prajapati commented on Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/.gitkeep
Took reference from somewhere and modified it according to requirements.

Gitkeep is used for tracking empty repos.
I will remove it and push the changes

2024-10-16 13:49 UTC, Avdhesh-Varshney commented on Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/.gitkeep
Ok remove it. Can you share your refrence here?

2024-10-16 13:53 UTC, mehul-m-prajapati commented on Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/.gitkeep
Type recipe sharing in chatgpt and it will give you skeleton code, then add features according to requirements

2024-10-16 16:05 UTC, mehul-m-prajapati commented on Angular-JS-Projects/Intermediate/Recipe-Sharing/src/assets/.gitkeep
@Avdhesh-Varshney : removed git keep file.

2024-10-17 14:02 UTC, Avdhesh-Varshney approved these changes

2024-10-17 14:02 UTC, merged