Completed File Upload and Download System using Node JS #46
Avdhesh-Varshney/WebMasterLog pull request #912
Opened 2024-10-15 11:23 UTC by aashutosh148

Closes: #46

- **Title:** File Upload and Download System using Node JS
- **Name:** Aashutosh Singh
- **Identify yourself:** GSSOC and Hacktober-Fest Contributor

### Describe the add-ons or changes you've made 📃

### Screenshots 📷

![Screenshot](https://github.com/aashutosh148/WebMasterLog/raw/file-upload-and-download-system-using-nodejs-46/Node-JS-Projects/Intermediate/File-Upload-And-Download-System/screenshot.webp)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-16 13:29 UTC, Avdhesh-Varshney requested changes
Enlist your project in readme file

2024-10-20 06:26 UTC, Avdhesh-Varshney commented
What's the update?

2024-10-20 14:26 UTC, aashutosh148 commented
> What's the update?

I was stuck in Mid Term exams, Sorry for the delay. I messed up at a few places but I think it's done. 
Let me know if any more changes needed.

2024-10-21 08:09 UTC, Avdhesh-Varshney requested changes

2024-10-21 08:09 UTC, Avdhesh-Varshney commented on Node-JS-Projects/Intermediate/File-Upload-And-Download-System/README.md
![image](https://github.com/user-attachments/assets/0c6ef99c-e2b3-4abb-87ee-e7f0a4ea92e8)

2024-10-21 14:55 UTC, Avdhesh-Varshney approved these changes

2024-10-21 14:55 UTC, merged