Added Gen AI Quiz Application with Gemini LLM in Next JS
Avdhesh-Varshney/WebMasterLog pull request #916
Opened 2024-10-15 16:23 UTC by J-B-Mugundh

Closes: 

- **Title:** Gen AI Quiz Application with Gemini LLM in Next JS
- **Name:** J B Mugundh
- **Idenitfy yourself:** GSSOC-EXTD

### Describe the add-ons or changes you've made 📃

- Gen AI Quiz Application with Gemini LLM in Next JS

###  Screenshots 📷
![](https://github.com/user-attachments/assets/7a6208da-ac94-436a-9e0b-ea22e1935198)
![](https://github.com/user-attachments/assets/112bd38b-0c04-46ca-9411-98e955b81401)
![](https://github.com/user-attachments/assets/2b714796-1dbc-4ed9-b65e-6bea45456a29)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-20 06:28 UTC, Avdhesh-Varshney requested changes
Add 1 ss file and README file. Also enlist your project in Nextjs readme file

2024-10-20 11:53 UTC, J-B-Mugundh commented
> Add 1 ss file and README file. Also enlist your project in Nextjs readme file

Ok sure! Lost track of this. Will finish it soon!

2024-10-20 12:12 UTC, J-B-Mugundh commented
@Avdhesh-Varshney Please check now!

2024-10-21 08:13 UTC, Avdhesh-Varshney requested changes
Enlist your project in Nextjs readme file

2024-10-21 08:13 UTC, Avdhesh-Varshney commented on Next-JS-Projects/Advanced/Gen-AI-Quiz-Application/README.md
![image](https://github.com/user-attachments/assets/2f95085e-8b00-4b7a-ab65-b6ddefed68ce)

2024-10-21 08:55 UTC, J-B-Mugundh commented
@Avdhesh-Varshney Updated!

2024-10-21 15:02 UTC, Avdhesh-Varshney requested changes

2024-10-21 15:02 UTC, Avdhesh-Varshney commented on Next-JS-Projects/README.md
Create row 2 for your project and leave other 2 columns free.

2024-10-22 07:49 UTC, J-B-Mugundh commented on Next-JS-Projects/README.md
> Create row 2 for your project and leave other 2 columns free.

Added!

2024-10-23 13:35 UTC, Avdhesh-Varshney approved these changes

2024-10-23 13:35 UTC, merged