[Intermediate React-Js]: I want to add Dynamic React Dashboard
Avdhesh-Varshney/WebMasterLog pull request #918
Opened 2024-10-15 19:17 UTC by inkerton

Closes: 

- **Title:** [Intermediate React-Js]: I want to add Dynamic React Dashboard 
- **Name:** inkerton
- **Idenitfy yourself:** GSSOC

### Describe the add-ons or changes you've made 📃
I added the dynamic dashboard project.

### Screenshots 📷

![image](https://github.com/user-attachments/assets/49686663-e79a-42f8-9b9e-0698420e632f)
![image](https://github.com/user-attachments/assets/179cb1fd-5173-4dc2-abcb-6069faf6df19)
[Link](https://www.loom.com/share/23d7e7dbc68640119c32007e737c052b?sid=16f3f673-d4e7-471d-a20b-e0e4d1cd037f)

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-17 07:44 UTC, inkerton commented
@Avdhesh-Varshney What changes do you required can you specify?

2024-10-20 06:30 UTC, Avdhesh-Varshney requested changes
Add 1 ss file and enlist your project in Reactjs readme file by reading the guidelines properly

2024-10-20 06:30 UTC, Avdhesh-Varshney commented on React-JS-Projects/Intermediate/Dynamic Dashboard/README.md
Follow readme template

2024-10-21 19:25 UTC, inkerton commented
@Avdhesh-Varshney  I have made the requested changes

2024-10-24 17:30 UTC, inkerton commented
@Avdhesh-Varshney Are there more changes Required?

2024-10-27 12:12 UTC, Avdhesh-Varshney commented
It can't be approved. Don't create more than 10 commits and not follow guidelines.
- Never commit directly in `main` branch.

2024-10-27 12:12 UTC, closed without merging