Add Wikipedia clone
Avdhesh-Varshney/WebMasterLog pull request #928
Opened 2024-10-16 14:13 UTC by amanver45

issue #835 
Closes: 
Title: Add Wikipedia clone
- Name: Aman Verma
- Identify yourself:GSSOC Contributor

### Describe the add-ons or changes you've made 📃
ADD WIKIPEDIA CLONE 

### Screenshots 📷
LIGHT MODE ![Screenshot 2024-10-11 104021](https://github.com/user-attachments/assets/d133fcc3-fd13-4362-ada2-6a7c4de59819)
DARK MODE ![Screenshot 2024-10-11 110939](https://github.com/user-attachments/assets/fc5a09c3-c5ca-4dca-b143-daf2134ab093)

- [x] My code follows the code style of this project.
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-16 14:14 UTC, amanver45 commented
@Avdhesh-Varshney sir  check this pr i update the changes in both folder and readme

2024-10-16 14:33 UTC, Avdhesh-Varshney requested changes

2024-10-16 14:33 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/README.md
README file is empty

2024-10-16 14:43 UTC, amanver45 commented on Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/README.md
update readme

2024-10-16 14:43 UTC, amanver45 commented
@Avdhesh-Varshney sir readme file is updated

2024-10-16 14:44 UTC, amanver45 commented
@Avdhesh-Varshney sir pls check it

2024-10-16 15:25 UTC, amanver45 commented
@Avdhesh-Varshney  sir check and merge it pls

2024-10-16 16:55 UTC, amanver45 commented
@Avdhesh-Varshney pls check it

2024-10-17 13:27 UTC, amanver45 commented
@Avdhesh-Varshney pls merge my pr

2024-10-17 14:07 UTC, Avdhesh-Varshney requested changes

2024-10-17 14:07 UTC, Avdhesh-Varshney commented on Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/README.md
> +<h4 align='center'>Developed By <b><i>Heli Detroja</i></b></h4>
Is it you?

2024-10-17 14:44 UTC, amanver45 commented on Vanilla-JS-Projects/Intermediate/Wikipedia-Clone/README.md
> +<h4 align='center'>Developed By <b><i>Heli Detroja</i></b></h4>
sry sir readme is now updated

2024-10-17 14:45 UTC, amanver45 commented
@Avdhesh-Varshney readme is now updated pls check

2024-10-17 14:46 UTC, amanver45 commented
@Avdhesh-Varshney pls check my pr and merge it

2024-10-17 15:39 UTC, amanver45 commented
@Avdhesh-Varshney ..

2024-10-17 16:24 UTC, amanver45 commented
@Avdhesh-Varshney  check it sir

2024-10-18 09:54 UTC, merged

2024-10-24 10:48 UTC, RadhikaMalpani1702 reviewed
@MastanSayyad  review this PR

2024-10-24 12:43 UTC, MastanSayyad commented
Hi @Avdhesh-Varshney Add only level 1 to all such PRs which has addition of projects instead of development on the repositories website