Added ProgressBar | Issue #879
Avdhesh-Varshney/WebMasterLog pull request #943
Opened 2024-10-17 20:57 UTC by Shariq2003

Closes: #879 

- **Title:** Added ProgressBar
- **Name:** Shariq
- **Idenitfy yourself:** 
GSSOC Ext

### Describe the add-ons or changes you've made 📃

I have added a progress bar.

https://github.com/user-attachments/assets/81b618a1-413b-4dc6-9af0-5e25aea88850

### Screenshots 📷

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist: ☑️

- [X] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CONTRIBUTING.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/WebMasterLog/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] This PR does not contain plagiarized content.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly wherever it was hard to understand.
- [X] My changes generate no new warnings.

### Note to reviewers 📄

2024-10-18 10:06 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review and merge this

2024-10-18 10:09 UTC, Avdhesh-Varshney requested changes
Nice Work. Make the same color of progressbar as of scrollbar

2024-10-18 10:09 UTC, Avdhesh-Varshney commented on webmasterlog/src/app/globals.css
Add this css using tailwind css.

2024-10-18 10:11 UTC, Shariq2003 commented on webmasterlog/src/app/globals.css
> Add this css using tailwind css.

okay changing

2024-10-18 10:21 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review and merge

2024-10-18 10:21 UTC, Shariq2003 commented
> Nice Work. Make the same color of progressbar as of scrollbar

Yes, its same

2024-10-19 10:05 UTC, Shariq2003 commented
@Avdhesh-Varshney sir, please review and merge this

2024-10-20 06:02 UTC, Avdhesh-Varshney approved these changes

2024-10-20 06:02 UTC, merged

2024-10-25 17:30 UTC, NEGRAH-S commented
@MastanSayyad ,  only one file changed and readymade component added Level 1 should be assigned

2024-10-25 18:33 UTC, Shariq2003 commented
> @MastanSayyad , only one file changed and readymade component added Level 1 should be assigned

@NEGRAH-S Sir, in Webdev everything is already implemented somewhere that doesn't mean it is like a cherry on the cake.

2024-10-27 00:17 UTC, MastanSayyad reviewed
It's fine